STAGE = "assign_species"
STAGE_VERSION = "0.1.0"

ERROR_SHAPEFILE_UNREADABLE = "E_SHAPEFILE_UNREADABLE"
ERROR_SPATIAL_JOIN_FAILED  = "E_SPATIAL_JOIN_FAILED"
ERROR_CSV_INVALID          = "E_CSV_INVALID"
