base_imgsz: 2048
scales: [0.5, 0.75, 1.0, 1.25, 1.5]
per_scale_conf: 0.15
per_scale_iou: 0.5
per_scale_max_det: 1000
conf: 0.70
iou: 0.5
final_max_det: 1000
wbf_iou: 0.55
wbf_score_thr: 0.001
edge_aware:
  enabled: true
  edge_band_rel: 0.12 # relative edge, percentage of the edge that included relative to total image size
  min_factor: 0.45 # reduce this to 0.45 conf threshold for edges 
  taper_rel: 0.0 # conf gradient extending from the center portion to the outside edge based on edge_band_rel. 0 means no gradient. 
post_fusion_nms:
  enabled: false
  iou: 0.5
mirror_pad:
  enabled: true
  pad_px: 512
