STAGE = "det_to_seg"
STAGE_VERSION = "1"

# Core File Errors
ERROR_MODEL_LOAD_FAILED = "MODEL_LOAD_FAILED"
ERROR_IMAGE_READ_FAILED = "IMAGE_READ_FAILED"
ERROR_DET_READ_FAILED = "DET_READ_FAILED"

# Processing/Logic Errors
ERROR_INFERENCE_FAILED = "INFERENCE_FAILED"
ERROR_EXPORT_FAILED = "EXPORT_FAILED"
ERROR_CFG_VALIDATION_FAILED = "CFG_VALIDATION_FAILED"
ERROR_UNKNOWN = "UNKNOWN"
