"""Segmentation-to-cutout stage contracts."""

STAGE = "seg_to_cut"
STAGE_VERSION = "0.1.0"

ERROR_CONFIG_INVALID = "E_CONFIG_INVALID"
ERROR_CSV_INVALID = "E_CSV_INVALID"
ERROR_DUPLICATE_DETECTION = "E_DUPLICATE_DETECTION"
ERROR_DUPLICATE_INPUT = "E_DUPLICATE_INPUT"
ERROR_IMAGE_MISSING = "E_IMAGE_MISSING"
ERROR_MASK_MISSING = "E_MASK_MISSING"
ERROR_IMAGE_INVALID = "E_IMAGE_INVALID"
ERROR_MASK_INVALID = "E_MASK_INVALID"
ERROR_DIMENSION_MISMATCH = "E_DIMENSION_MISMATCH"
ERROR_UNKNOWN_MASK_VALUE = "E_UNKNOWN_MASK_VALUE"
ERROR_EMPTY_BOUNDING_BOX = "E_EMPTY_BOUNDING_BOX"

