STAGE = "raw_to_jpg"
STAGE_VERSION = "1"

# Error codes
ERROR_RAW_READ_FAILED = "RAW_READ_FAILED"
ERROR_CFG_VALIDATION_FAILED = "ERROR_CFG_VALIDATION_FAILED"
ERROR_DNG_CONVERSION_FAILED = "DNG_CONVERSION_FAILED"
ERROR_JPG_DEVELOPMENT_FAILED = "JPG_DEVELOPMENT_FAILED"
ERROR_RT_TIMEOUT = "RAWTHERAPEE_TIMEOUT"
ERROR_RT_NOT_FOUND = "RAWTHERAPEE_NOT_FOUND"
ERROR_FILE_NOT_FOUND = "FILE_NOT_FOUND"
ERROR_INVALID_RAW = "INVALID_RAW_FORMAT"
ERROR_UNKNOWN = "UNKNOWN"
