STAGE = "jpg_to_det"
STAGE_VERSION = "1"

# Error codes
ERROR_MODEL_LOAD_FAILED = "MODEL_LOAD_FAILED"
ERROR_IMAGE_READ_FAILED = "IMAGE_READ_FAILED"
ERROR_INFERENCE_FAILED = "INFERENCE_FAILED"
ERROR_EXPORT_FAILED = "EXPORT_FAILED"
ERROR_CFG_VALIDATION_FAILED = "CFG_VALIDATION_FAILED"
ERROR_UNKNOWN = "UNKNOWN"
