#!/usr/bin/env bash
set -euo pipefail

echo "[PG-INIT] Bootstrap on $(hostname -f) at $(date)"

# ------------------------------------------------------------------------------
# 0) Config
# ------------------------------------------------------------------------------
LOG_DIR="/project/dash_agir/logs/pg_cluster_init"
PG_ROOT="/project/dash_agir/postgres"
PGDATA="${PG_ROOT}/pgdata_agir"

DB_NAME="${DB_NAME:-agir}"
ADMIN_DB="postgres"

mkdir -p "$LOG_DIR" "$PG_ROOT" "$PGDATA"
chmod 700 "$PGDATA" || true

# Temporary port just for bootstrap start
BOOT_PORT="${BOOT_PORT:-$(( 50000 + RANDOM % 1000 ))}"
PGLOG="${LOG_DIR}/pg_init_$(date +%Y%m%d_%H%M%S).log"

# ------------------------------------------------------------------------------
# 1) Load PostgreSQL tools
# ------------------------------------------------------------------------------
module load postgresql

for bin in initdb pg_ctl psql; do
  command -v "$bin" >/dev/null 2>&1 || {
    echo "[ERROR] Missing binary: $bin (check module load postgresql)"
    exit 1
  }
done

# ------------------------------------------------------------------------------
# 2) Read password from ~/.pgpass (wildcards supported)
#    We just grab the first entry for this user.
# ------------------------------------------------------------------------------
PGPASS_FILE="${HOME}/.pgpass"
if [[ ! -f "$PGPASS_FILE" ]]; then
  echo "[ERROR] ~/.pgpass not found at $PGPASS_FILE"
  exit 1
fi
chmod 600 "$PGPASS_FILE" || true

DB_PASSWORD="$(
  awk -F: -v u="$USER" '
    $4==u && $5!="" {print $5; exit}
  ' "$PGPASS_FILE"
)"

if [[ -z "${DB_PASSWORD:-}" ]]; then
  echo "[ERROR] Could not extract a password for user '${USER}' from ~/.pgpass"
  echo "        Ensure a wildcard line exists, e.g.: *:*:*:${USER}:YOUR_PASSWORD"
  exit 1
fi

# ------------------------------------------------------------------------------
# 3) Initialize cluster if missing
# ------------------------------------------------------------------------------
if [[ ! -f "${PGDATA}/PG_VERSION" ]]; then
  echo "[PG-INIT] initdb at ${PGDATA}"
  initdb -D "$PGDATA" --encoding=UTF8 --no-locale

  # postgresql.conf additions (no fixed port here; server job provides -p each run)
  {
    echo ""
    echo "# Added by pg_cluster_init_agir.sh"
    echo "listen_addresses = '*'"
    echo "max_connections = 50"
    echo "shared_buffers = 256MB"
    echo "work_mem = 32MB"
    # Optional: use SCRAM if available; harmless if left as md5 in pg_hba
    echo "password_encryption = 'scram-sha-256'"
  } >> "${PGDATA}/postgresql.conf"

  # pg_hba.conf policy (local trust for on-node admin; TCP requires password)
  cat > "${PGDATA}/pg_hba.conf" <<'EOF'
# pg_hba.conf generated by pg_cluster_init_agir.sh

# Local connections (Unix socket) – trusted for on-node admin/bootstrap
local   all             all                                     trust

# Loopback requires password
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5

# Cluster access requires password
host    all             all             0.0.0.0/0               md5
host    all             all             ::/0                    md5
EOF

  echo "[PG-INIT] Cluster initialized."
else
  echo "[PG-INIT] Existing cluster found at ${PGDATA} (skipping initdb)"
fi

# ------------------------------------------------------------------------------
# 4) Start postgres on a temporary port for bootstrap
# ------------------------------------------------------------------------------
echo "[PG-INIT] Starting postgres on temporary port ${BOOT_PORT}"
pg_ctl -D "$PGDATA" -o "-p ${BOOT_PORT}" -l "$PGLOG" start

cleanup() {
  echo "[PG-INIT] Stopping postgres..."
  pg_ctl -D "$PGDATA" stop -m fast >/dev/null 2>&1 || true
}
trap cleanup EXIT INT TERM

# Readiness via local socket (no host)
echo "[PG-INIT] Waiting for readiness..."
for i in {1..30}; do
  if psql -p "${BOOT_PORT}" -d "${ADMIN_DB}" -U "${USER}" -c "SELECT 1;" >/dev/null 2>&1; then
    echo "[PG-INIT] Postgres is up."
    break
  fi
  sleep 1
  if [[ "$i" -eq 30 ]]; then
    echo "[ERROR] Postgres did not become ready. Tail log:"
    tail -n 60 "$PGLOG" || true
    exit 1
  fi
done

# ------------------------------------------------------------------------------
# 5) Set role password (idempotent)
#    Uses local socket trust; sets password for TCP md5/scram auth later.
# ------------------------------------------------------------------------------
echo "[PG-INIT] Setting password for role '${USER}'"
psql -p "${BOOT_PORT}" -d "${ADMIN_DB}" -U "${USER}" -v ON_ERROR_STOP=1 \
  -c "ALTER ROLE \"${USER}\" WITH PASSWORD '${DB_PASSWORD}';"

# ------------------------------------------------------------------------------
# 6) Ensure DB exists (check from postgres)
# ------------------------------------------------------------------------------
echo "[PG-INIT] Ensuring DB '${DB_NAME}' exists"
DB_EXISTS="$(
  psql -p "${BOOT_PORT}" -d "${ADMIN_DB}" -U "${USER}" -tAc \
    "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}';" \
  | tr -d '[:space:]' || true
)"

if [[ "$DB_EXISTS" != "1" ]]; then
  psql -p "${BOOT_PORT}" -d "${ADMIN_DB}" -U "${USER}" -v ON_ERROR_STOP=1 \
    -c "CREATE DATABASE \"${DB_NAME}\";"
  echo "[PG-INIT] Created DB '${DB_NAME}'"
else
  echo "[PG-INIT] DB '${DB_NAME}' already exists"
fi

# ------------------------------------------------------------------------------
# 7) Ensure schemas exist
# ------------------------------------------------------------------------------
echo "[PG-INIT] Ensuring schemas exist in '${DB_NAME}'"
psql -p "${BOOT_PORT}" -d "${DB_NAME}" -U "${USER}" -v ON_ERROR_STOP=1 <<'SQL'
CREATE SCHEMA IF NOT EXISTS source;
CREATE SCHEMA IF NOT EXISTS processed;
CREATE SCHEMA IF NOT EXISTS release;
CREATE SCHEMA IF NOT EXISTS logs;
CREATE SCHEMA IF NOT EXISTS registry;
CREATE SCHEMA IF NOT EXISTS report;
CREATE SCHEMA IF NOT EXISTS ops;
SQL

# ------------------------------------------------------------------------------
# 8) Write coords env WITHOUT claiming a stable port
#    (Your server sbatch job should overwrite pg_coords.env every run.)
# ------------------------------------------------------------------------------
COORD_FILE="${PG_ROOT}/pg_coords.env"
cat > "$COORD_FILE" <<EOF
# Auto-generated by pg_cluster_init_agir.sh at $(date)
export PGDATA=${PGDATA}
export PGDATABASE=${DB_NAME}
export PGUSER=${USER}
# NOTE: PGHOST/PGPORT are determined per server job run and will be written by it.
# Password lives in ~/.pgpass (wildcards supported).
EOF
chmod 600 "$COORD_FILE" || true

echo "[PG-INIT] Wrote ${COORD_FILE}"
cat "$COORD_FILE"

echo "[PG-INIT] Cluster bootstrap complete."
