#!/usr/bin/env bash
# Exit on command errors, unset variables, and pipeline failures.
set -euo pipefail

echo "[PG-INIT] Bootstrap on $(hostname -f) at $(date)"

# ------------------------------------------------------------------------------
# 0) Config
# ------------------------------------------------------------------------------
LOG_DIR="/project/dash_agir/logs/pg_cluster_init"
PG_ROOT="/project/dash_agir/postgres"
PGDATA="${PG_ROOT}/pgdata_agir"

DB_NAME="${DB_NAME:-agir}"
ADMIN_DB="postgres"

mkdir -p "$LOG_DIR" "$PG_ROOT" "$PGDATA"
chmod 700 "$PGDATA" || true

# Temporary port just for bootstrap start
BOOT_PORT="${BOOT_PORT:-$(( 50000 + RANDOM % 1000 ))}"
PGLOG="${LOG_DIR}/pg_init_$(date +%Y%m%d_%H%M%S).log"

# ------------------------------------------------------------------------------
# 1) Load PostgreSQL tools
# ------------------------------------------------------------------------------
module load postgresql

for bin in initdb pg_ctl psql; do
  command -v "$bin" >/dev/null 2>&1 || {
    echo "[ERROR] Missing binary: $bin (check module load postgresql)"
    exit 1
  }
done

# ------------------------------------------------------------------------------
# 2) Read password from ~/.pgpass (wildcards supported)
# ------------------------------------------------------------------------------
PGPASS_FILE="${HOME}/.pgpass"
if [[ ! -f "$PGPASS_FILE" ]]; then
  echo "[ERROR] ~/.pgpass not found at $PGPASS_FILE"
  exit 1
fi
chmod 600 "$PGPASS_FILE" || true

DB_PASSWORD="$(
  awk -F: -v u="$USER" '
    $4==u && $5!="" {print $5; exit}
  ' "$PGPASS_FILE"
)"

if [[ -z "${DB_PASSWORD:-}" ]]; then
  echo "[ERROR] Could not extract a password for user '${USER}' from ~/.pgpass"
  echo "        Ensure a wildcard line exists, e.g.: *:*:*:${USER}:YOUR_PASSWORD"
  exit 1
fi

# ------------------------------------------------------------------------------
# 3) Initialize cluster if missing
# ------------------------------------------------------------------------------
if [[ ! -f "${PGDATA}/PG_VERSION" ]]; then
  echo "[PG-INIT] initdb at ${PGDATA}"
  initdb -D "$PGDATA" --encoding=UTF8 --no-locale

  # Safe defaults in postgresql.conf
  # - local-only by default
  # - leader job can override listen/port via -c flags each run
  {
    echo ""
    echo "# Added by create_db_server.sh"
    echo "listen_addresses = '127.0.0.1'"
    echo "max_connections = 50"
    echo "shared_buffers = 256MB"
    echo "work_mem = 32MB"
    echo "password_encryption = 'scram-sha-256'"
  } >> "${PGDATA}/postgresql.conf"

  echo "[PG-INIT] Cluster initialized."
else
  echo "[PG-INIT] Existing cluster found at ${PGDATA} (skipping initdb)"
fi

# ------------------------------------------------------------------------------
# 4) Write a TEMPORARY pg_hba.conf for bootstrap only
#    We need a way to connect before a password exists. We use local trust for
#    the bootstrap phase, then replace it with a hardened config after setting
#    the password.
# ------------------------------------------------------------------------------
HBA_FILE="${PGDATA}/pg_hba.conf"

cat > "${HBA_FILE}" <<'EOF'
# pg_hba.conf (bootstrap) generated by create_db_server.sh
# Purpose: allow local bootstrap connections to set initial passwords.
# This file will be replaced with a hardened config later in this script.

local   all   all                         trust
host    all   all   127.0.0.1/32          trust
host    all   all   ::1/128               trust
EOF
chmod 600 "${HBA_FILE}" || true

# ------------------------------------------------------------------------------
# 5) Start postgres on a temporary port for bootstrap
# ------------------------------------------------------------------------------
echo "[PG-INIT] Starting postgres on temporary port ${BOOT_PORT}"
pg_ctl -D "$PGDATA" -o "-p ${BOOT_PORT} -c listen_addresses='127.0.0.1'" -l "$PGLOG" start

cleanup() {
  echo "[PG-INIT] Stopping postgres..."
  pg_ctl -D "$PGDATA" stop -m fast >/dev/null 2>&1 || true
}
trap cleanup EXIT INT TERM

# Readiness via loopback
echo "[PG-INIT] Waiting for readiness..."
for i in {1..30}; do
  if psql -h 127.0.0.1 -p "${BOOT_PORT}" -d "${ADMIN_DB}" -U "${USER}" -c "SELECT 1;" >/dev/null 2>&1; then
    echo "[PG-INIT] Postgres is up."
    break
  fi
  sleep 1
  if [[ "$i" -eq 30 ]]; then
    echo "[ERROR] Postgres did not become ready. Tail log:"
    tail -n 60 "$PGLOG" || true
    exit 1
  fi
done

# ------------------------------------------------------------------------------
# 6) Set role password (idempotent)
# ------------------------------------------------------------------------------
echo "[PG-INIT] Setting password for role '${USER}'"
psql -h 127.0.0.1 -p "${BOOT_PORT}" -d "${ADMIN_DB}" -U "${USER}" -v ON_ERROR_STOP=1 \
  -c "ALTER ROLE \"${USER}\" WITH PASSWORD '${DB_PASSWORD}';"

# ------------------------------------------------------------------------------
# 7) Replace pg_hba.conf with a HARDENED baseline
#    - No trust
#    - SCRAM everywhere
#    - Local + loopback only (leader job can override per-job to allow node-to-node)
# ------------------------------------------------------------------------------
cat > "${HBA_FILE}" <<'EOF'
# pg_hba.conf (hardened baseline) generated by create_db_server.sh
# Safe default: local-only access with SCRAM.
# Your sbatch "leader" script may override/replace hba_file per job to allow
# only allocated nodes.

local   all   all                         scram-sha-256
host    all   all   127.0.0.1/32          scram-sha-256
host    all   all   ::1/128               scram-sha-256
EOF
chmod 600 "${HBA_FILE}" || true

# Reload config so hardening takes effect immediately
pg_ctl -D "$PGDATA" reload >/dev/null 2>&1 || true
echo "[PG-INIT] Hardened pg_hba.conf installed (local-only + SCRAM)."

# ------------------------------------------------------------------------------
# 8) Ensure DB exists (check from postgres)
# ------------------------------------------------------------------------------
echo "[PG-INIT] Ensuring DB '${DB_NAME}' exists"
DB_EXISTS="$(
  psql -h 127.0.0.1 -p "${BOOT_PORT}" -d "${ADMIN_DB}" -U "${USER}" -tAc \
    "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}';" \
  | tr -d '[:space:]' || true
)"

if [[ "$DB_EXISTS" != "1" ]]; then
  psql -h 127.0.0.1 -p "${BOOT_PORT}" -d "${ADMIN_DB}" -U "${USER}" -v ON_ERROR_STOP=1 \
    -c "CREATE DATABASE \"${DB_NAME}\";"
  echo "[PG-INIT] Created DB '${DB_NAME}'"
else
  echo "[PG-INIT] DB '${DB_NAME}' already exists"
fi

# ------------------------------------------------------------------------------
# 9) Ensure schemas exist
# ------------------------------------------------------------------------------
echo "[PG-INIT] Ensuring schemas exist in '${DB_NAME}'"
psql -h 127.0.0.1 -p "${BOOT_PORT}" -d "${DB_NAME}" -U "${USER}" -v ON_ERROR_STOP=1 <<'SQL'
CREATE SCHEMA IF NOT EXISTS source;
CREATE SCHEMA IF NOT EXISTS processed;
CREATE SCHEMA IF NOT EXISTS release;
CREATE SCHEMA IF NOT EXISTS logs;
CREATE SCHEMA IF NOT EXISTS registry;
CREATE SCHEMA IF NOT EXISTS report;
CREATE SCHEMA IF NOT EXISTS ops;
SQL

# ------------------------------------------------------------------------------
# 10) Write coords env (no host/port, leader overwrites those per run)
# ------------------------------------------------------------------------------
COORD_FILE="${PG_ROOT}/pg_coords.env"
cat > "$COORD_FILE" <<EOF
# Auto-generated by create_db_server.sh at $(date)
export PGDATA=${PGDATA}
export PGDATABASE=${DB_NAME}
export PGUSER=${USER}
# NOTE: PGHOST/PGPORT are determined per server job run and will be written by it.
# Auth uses SCRAM; password lives in ~/.pgpass (wildcards supported).
EOF
chmod 600 "$COORD_FILE" || true

echo "[PG-INIT] Wrote ${COORD_FILE}"
cat "$COORD_FILE"

echo "[PG-INIT] Cluster bootstrap complete."
