#!/usr/bin/env bash
#SBATCH --job-name=pg_server_agir
#SBATCH --account=dash_agir
#SBATCH --time=12:00:00
#SBATCH --cpus-per-task=2
#SBATCH --mem=8G
#SBATCH --output=/project/dash_agir/logs/pg_server/agir_%x_%j.out.log
#SBATCH --error=/project/dash_agir/logs/pg_server/agir_%x_%j.err.log

set -euo pipefail
unset PGHOST PGDATABASE PGUSER PGPASSWORD PGPORT
export PGPASSFILE="${HOME}/.pgpass"
export PGCONNECT_TIMEOUT=3

echo "[PG-SERVER] Starting on $(hostname -f) at $(date)"

# ------------------------------------------------------------------------------
# 1) Activate env / load PostgreSQL
# ------------------------------------------------------------------------------
HPC_ROOT="/project/dash_agir/${USER}"
ENV_NAME="${ENV_NAME:-agir_pipeline}"
HPC_VENV="${HPC_ROOT}/software/uv/venvs/${ENV_NAME}"
source "${HPC_VENV}/bin/activate"

module load postgresql

# ------------------------------------------------------------------------------
# 2) Static config
# ------------------------------------------------------------------------------
LOG_DIR="/project/dash_agir/logs"
PG_ROOT="/project/dash_agir/postgres"
mkdir -p "$LOG_DIR" "$PG_ROOT"

export PGDATA="${PG_ROOT}/pgdata_agir"
DB_NAME="agir"
ADMIN_DB="postgres"
COORD_FILE="${PG_ROOT}/pg_coords.env"
PGLOG="${PGDATA}/postgres.log"

# ------------------------------------------------------------------------------
# 3) Sanity check
# ------------------------------------------------------------------------------
for bin in pg_ctl psql; do
  command -v "$bin" >/dev/null 2>&1 || {
    echo "[ERROR] Missing binary: $bin (check module load postgresql)"
    exit 1
  }
done

if [[ ! -f "${PGPASSFILE}" ]]; then
  echo "[ERROR] ${PGPASSFILE} not found."
  exit 1
fi
chmod 600 "${PGPASSFILE}" || true

# ------------------------------------------------------------------------------
# 4) Require cluster to already exist (bootstrap is separate script)
# ------------------------------------------------------------------------------
if [[ ! -d "$PGDATA" || ! -f "$PGDATA/PG_VERSION" ]]; then
  echo "[ERROR] PGDATA is not initialized: ${PGDATA}"
  echo "        Run your one-time pg_cluster_init_agir.sh first."
  exit 1
fi

echo "[PG-SERVER] Using existing cluster at $PGDATA"

# ------------------------------------------------------------------------------
# 5) If Postgres is already running for this PGDATA, don't start a second one.
#    Write coords for the existing server and keep the job alive.
# ------------------------------------------------------------------------------
if pg_ctl -D "$PGDATA" status >/dev/null 2>&1; then
  RUN_PORT="$(cat "${PGDATA}/.server_port" 2>/dev/null || awk 'NR==4{print $1}' "$PGDATA/postmaster.pid" 2>/dev/null || true)"
  RUN_HOST="$(cat "${PGDATA}/.server_host" 2>/dev/null || hostname -f)"

  # If the marker files don't exist yet, create them now for future runs
  [[ -f "${PGDATA}/.server_host" ]] || echo "$RUN_HOST" > "${PGDATA}/.server_host"
  [[ -f "${PGDATA}/.server_port" ]] || echo "$RUN_PORT" > "${PGDATA}/.server_port"
  chmod 600 "${PGDATA}/.server_host" "${PGDATA}/.server_port" 2>/dev/null || true

  echo "[PG-SERVER] Postgres already running for $PGDATA on ${RUN_HOST}:${RUN_PORT}"
  echo "[PG-SERVER] Writing coords and staying alive."

  cat > "$COORD_FILE" <<EOF
# Auto-generated by pg_server_agir (existing server) at $(date)
export PGHOST=${RUN_HOST}
export PGPORT=${RUN_PORT}
export PGDATABASE=${DB_NAME}
export PGUSER=${USER}
EOF
  chmod 600 "$COORD_FILE" || true
  cat "$COORD_FILE"

  sleep infinity
fi

# ------------------------------------------------------------------------------
# 6) Start Postgres on a random port
# ------------------------------------------------------------------------------
export PGPORT=$(( 50000 + RANDOM % 1000 ))
PGHOST_FQDN="$(hostname -f)"

# If pidfile exists but pg_ctl says not running, it's stale. Remove it.
if [[ -f "$PGDATA/postmaster.pid" ]] && ! pg_ctl -D "$PGDATA" status >/dev/null 2>&1; then
  echo "[PG-SERVER] Stale postmaster.pid detected; removing it."
  rm -f "$PGDATA/postmaster.pid" "$PGDATA/postmaster.opts"
fi

echo "[PG-SERVER] Starting Postgres on ${PGHOST_FQDN}:${PGPORT}"
pg_ctl -D "$PGDATA" -o "-p ${PGPORT}" -l "$PGLOG" start

# Record host/port so future runs can report the correct host even from other nodes
echo "$PGHOST_FQDN" > "${PGDATA}/.server_host"
echo "${PGPORT}"   > "${PGDATA}/.server_port"
chmod 600 "${PGDATA}/.server_host" "${PGDATA}/.server_port" || true

# ------------------------------------------------------------------------------
# 7) Readiness check (connect to ADMIN_DB)
#    -w = never prompt (forces pgpass to be used)
# ------------------------------------------------------------------------------
echo "[PG-SERVER] Waiting for Postgres to accept connections..."
ready=0
for i in {1..30}; do
  echo "[PG-SERVER] Readiness attempt ${i}..."
  if psql -w "host=${PGHOST_FQDN} port=${PGPORT} dbname=${ADMIN_DB} user=${USER}" \
        -v ON_ERROR_STOP=1 -c "SELECT 1;" >/dev/null; then
    ready=1
    break
  fi
  sleep 1
done

if [[ "$ready" -ne 1 ]]; then
  echo "[ERROR] Postgres failed readiness check. Tail of log:"
  tail -n 50 "$PGLOG" || true
  exit 1
fi

echo "[PG-SERVER] Postgres is UP"

# ------------------------------------------------------------------------------
# 8) Ensure primary database exists (check from postgres)
# ------------------------------------------------------------------------------
echo "[PG-SERVER] Ensuring DB '${DB_NAME}' exists..."

DB_EXISTS="$(
  psql -w "host=${PGHOST_FQDN} port=${PGPORT} dbname=${ADMIN_DB} user=${USER}" \
       -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}';" \
  | tr -d '[:space:]' || true
)"

if [[ "$DB_EXISTS" != "1" ]]; then
  echo "[PG-SERVER] Creating DB '${DB_NAME}'"
  psql -w "host=${PGHOST_FQDN} port=${PGPORT} dbname=${ADMIN_DB} user=${USER}" \
       -v ON_ERROR_STOP=1 -c "CREATE DATABASE \"${DB_NAME}\";"
else
  echo "[PG-SERVER] Database '${DB_NAME}' already exists"
fi

# ------------------------------------------------------------------------------
# 9) Ensure schemas exist in agir
# ------------------------------------------------------------------------------
echo "[PG-SERVER] Ensuring schemas exist in '${DB_NAME}'"
psql -w "host=${PGHOST_FQDN} port=${PGPORT} dbname=${DB_NAME} user=${USER}" \
     -v ON_ERROR_STOP=1 <<'SQL'
CREATE SCHEMA IF NOT EXISTS source;
CREATE SCHEMA IF NOT EXISTS processed;
CREATE SCHEMA IF NOT EXISTS release;
CREATE SCHEMA IF NOT EXISTS logs;
CREATE SCHEMA IF NOT EXISTS registry;
CREATE SCHEMA IF NOT EXISTS report;
CREATE SCHEMA IF NOT EXISTS ops;
SQL

echo "[PG-SERVER] Schemas ensured."

# ------------------------------------------------------------------------------
# 10) Write connection coordinates (no secrets)
# ------------------------------------------------------------------------------
cat > "$COORD_FILE" <<EOF
# Auto-generated by pg_server_agir at $(date)
export PGHOST=${PGHOST_FQDN}
export PGPORT=${PGPORT}
export PGDATABASE=${DB_NAME}
export PGUSER=${USER}
EOF
chmod 600 "$COORD_FILE" || true

echo "[PG-SERVER] Wrote connection info to ${COORD_FILE}:"
cat "$COORD_FILE"

# ------------------------------------------------------------------------------
# 11) Graceful shutdown handler + keep alive
# ------------------------------------------------------------------------------
cleanup() {
  echo "[PG-SERVER] Shutting down Postgres..."
  pg_ctl -D "$PGDATA" stop -m fast || true
}
trap cleanup EXIT INT TERM

echo "[PG-SERVER] Server running."
echo "[PG-SERVER] Connect from elsewhere with:"
echo "  source ${COORD_FILE}"
echo "  psql -h ${PGHOST_FQDN} -p ${PGPORT} -d ${DB_NAME} -U ${USER}"

sleep infinity
