#!/usr/bin/env bash
#SBATCH --job-name=pg_server_agir
#SBATCH --account=dash_agir
#SBATCH --time=4:00:00
#SBATCH --cpus-per-task=2
#SBATCH --mem=8G
#SBATCH --output=/project/dash_agir/logs/pg_server/agir_%x_%j.out.log
#SBATCH --error=/project/dash_agir/logs/pg_server/agir_%x_%j.err.log

# Exit on command errors, unset variables, and pipeline failures.
set -euo pipefail
unset PGHOST PGDATABASE PGUSER PGPASSWORD PGPORT
export PGPASSFILE="${HOME}/.pgpass"
export PGCONNECT_TIMEOUT=3
export PGGSSENCMODE="${PGGSSENCMODE:-disable}"

echo "[PG-SERVER] Starting on $(hostname -f) at $(date)"

# ------------------------------------------------------------------------------
# 1) Activate env / load PostgreSQL
# ------------------------------------------------------------------------------
HPC_ROOT="/project/dash_agir/${USER}"
ENV_NAME="${ENV_NAME:-agir_pipeline}"
HPC_VENV="${HPC_ROOT}/software/uv/venvs/${ENV_NAME}"
source "${HPC_VENV}/bin/activate"

module load postgresql

# ------------------------------------------------------------------------------
# 2) Static config
# ------------------------------------------------------------------------------
LOG_DIR="/project/dash_agir/logs"
PG_ROOT="/project/dash_agir/postgres"
mkdir -p "$LOG_DIR" "$PG_ROOT"

export PGDATA="${PG_ROOT}/pgdata_agir"
DB_NAME="${DB_NAME:-agir}"
ADMIN_DB="${ADMIN_DB:-postgres}"

# Who clients will connect as (must exist in DB + have a password in ~/.pgpass)
ADMIN_USER="${ADMIN_USER:-${USER}}"

COORD_FILE="${PG_ROOT}/pg_coords.env"
PGLOG="${PGDATA}/postgres.log"

# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------
pg_leader_ip() {
  # Choose a routable IPv4 for node-to-node connections
  hostname -I | awk '{print $1}'
}

psql_ok() {
  local host="$1"
  local port="$2"
  local db="$3"
  local user="$4"
  psql -w "host=${host} port=${port} dbname=${db} user=${user}" -v ON_ERROR_STOP=1 -c "SELECT 1;" >/dev/null
}

write_coords() {
  local host="$1"
  local port="$2"
  cat > "$COORD_FILE" <<EOF
# Auto-generated by pg_server_agir at $(date)
# WARNING:
# This Postgres instance is ephemeral.
# Accessible from private internal networks + valid DB roles/passwords.

export PGHOST=${host}
export PGPORT=${port}
export PGDATABASE=${DB_NAME}
export PGUSER=${ADMIN_USER}
export PGJOBID=${SLURM_JOB_ID:-}
EOF
  chmod 600 "$COORD_FILE" || true
  echo "[PG-SERVER] Wrote connection info to ${COORD_FILE}:"
  cat "$COORD_FILE"
}

# ------------------------------------------------------------------------------
# 3) Sanity check
# ------------------------------------------------------------------------------
for bin in pg_ctl psql initdb; do
  command -v "$bin" >/dev/null 2>&1 || {
    echo "[ERROR] Missing binary: $bin (check module load postgresql)"
    exit 1
  }
done

if [[ ! -f "${PGPASSFILE}" ]]; then
  echo "[ERROR] ${PGPASSFILE} not found."
  exit 1
fi
chmod 600 "${PGPASSFILE}" || true

# ------------------------------------------------------------------------------
# 4) Require cluster to already exist (bootstrap is separate script)
# ------------------------------------------------------------------------------
if [[ ! -d "$PGDATA" || ! -f "$PGDATA/PG_VERSION" ]]; then
  echo "[ERROR] PGDATA is not initialized: ${PGDATA}"
  echo "        Run your one-time create_db_server.sh first."
  exit 1
fi

echo "[PG-SERVER] Using existing cluster at $PGDATA"

# ------------------------------------------------------------------------------
# 5) Detect an existing running server safely (even if it's on a different node)
#    IMPORTANT: With shared PGDATA, pg_ctl status on this node is NOT reliable.
# ------------------------------------------------------------------------------
MARK_HOST_FILE="${PGDATA}/.server_host"
MARK_PORT_FILE="${PGDATA}/.server_port"
LOCKDIR="${PGDATA}/.server_lock"

acquire_lock_or_recover() {
  # Try to take the lock
  if mkdir "$LOCKDIR" 2>/dev/null; then
    return 0
  fi

  echo "[PG-SERVER][WARN] Lock exists: $LOCKDIR" >&2

  # If markers exist, probe whether server is actually reachable.
  if [[ -f "$MARK_HOST_FILE" && -f "$MARK_PORT_FILE" ]]; then
    local run_host run_port
    run_host="$(cat "$MARK_HOST_FILE" 2>/dev/null || true)"
    run_port="$(cat "$MARK_PORT_FILE" 2>/dev/null || true)"

    if [[ -n "${run_host:-}" && -n "${run_port:-}" ]]; then
      echo "[PG-SERVER][INFO] Found markers: ${run_host}:${run_port} (probing...)" >&2

      # If reachable, another server is truly running. Refuse to start.
      if psql_ok "$run_host" "$run_port" "$ADMIN_DB" "$ADMIN_USER" >/dev/null 2>&1; then
        echo "[PG-SERVER][ERROR] Existing server is reachable; refusing to start a second instance." >&2
        echo "[PG-SERVER][INFO] Connect using markers: ${run_host}:${run_port}" >&2
        exit 3
      fi

      echo "[PG-SERVER][WARN] Markers not reachable; treating lock as stale." >&2
    fi
  else
    echo "[PG-SERVER][WARN] No markers present; lock may be stale." >&2
  fi

  # Stale-lock recovery: remove lock and try again once
  echo "[PG-SERVER][WARN] Removing stale lock: $LOCKDIR" >&2
  rmdir "$LOCKDIR" 2>/dev/null || {
    echo "[PG-SERVER][ERROR] Could not remove lock (not empty?). Inspect: ls -la $LOCKDIR" >&2
    exit 3
  }

  if mkdir "$LOCKDIR" 2>/dev/null; then
    echo "[PG-SERVER][INFO] Re-acquired lock after stale recovery." >&2
    return 0
  fi

  echo "[PG-SERVER][ERROR] Failed to acquire lock even after recovery." >&2
  exit 3
}

acquire_lock_or_recover

echo "${SLURM_JOB_ID:-unknown}" > "$PGDATA/.lock_jobid" 2>/dev/null || true
echo "$(hostname -f)"          > "$PGDATA/.lock_host"  2>/dev/null || true
date                           > "$PGDATA/.lock_created_at" 2>/dev/null || true
chmod 600 "$PGDATA/.lock_"* 2>/dev/null || true

cleanup() {
  echo "[PG-SERVER] Shutting down Postgres..."
  pg_ctl -D "$PGDATA" stop -m fast >/dev/null 2>&1 || true
}

# Install traps immediately so lock always gets released even if job is killed mid-startup
trap 'cleanup; rmdir "$LOCKDIR" 2>/dev/null || true' EXIT INT TERM HUP QUIT

# ------------------------------------------------------------------------------
# 6) Start Postgres (job-scoped host/port + job-scoped pg_hba allowlist)
# ------------------------------------------------------------------------------
LEADER_IP="$(pg_leader_ip)"
if [[ -z "${LEADER_IP:-}" ]]; then
  echo "[ERROR] Could not determine leader IP via hostname -I" >&2
  exit 1
fi

# Fixed port for all runs (choose one and keep it)
PGPORT="${PGPORT:-54338}"
export PGPORT

# Fail fast if something is already listening on that port on THIS node
if command -v ss >/dev/null 2>&1; then
  if ss -ltn 2>/dev/null | awk '{print $4}' | grep -q ":${PGPORT}$"; then
    echo "[ERROR] Port ${PGPORT} already in use on $(hostname -f). Pick another PGPORT." >&2
    exit 2
  fi
fi


HBA_FILE="${PGDATA}/pg_hba_job_${SLURM_JOB_ID:-manual}.conf"
{
  echo "# Generated: $(date)"
  echo "# Policy: allow only private internal networks + require SCRAM"
  echo "# Local (unix socket) requires SCRAM"
  echo "local   all   all                         scram-sha-256"

  echo "# Loopback requires SCRAM"
  echo "host    all   all   127.0.0.1/32          scram-sha-256"
  echo "host    all   all   ::1/128               scram-sha-256"

  echo "# Private RFC1918 IPv4 ranges (common internal cluster nets)"
  echo "host    all   all   10.0.0.0/8            scram-sha-256"
  echo "host    all   all   172.16.0.0/12         scram-sha-256"
  echo "host    all   all   192.168.0.0/16        scram-sha-256"
  echo "host    all   all   199.245.99.3/32       scram-sha-256"

  echo "# (Optional) If SCINet uses IPv6 internally, keep this; otherwise you can omit it."
  echo "host    all   all   fc00::/7              scram-sha-256"

  echo "# Default deny"
  echo "host    all   all   0.0.0.0/0             reject"
  echo "host    all   all   ::/0                  reject"
} > "$HBA_FILE"

chmod 600 "$HBA_FILE" || true

if [[ -f "$PGDATA/postmaster.pid" ]] && ! pg_ctl -D "$PGDATA" status >/dev/null 2>&1; then
  echo "[PG-SERVER][WARN] Stale postmaster.pid detected; removing it."
  rm -f "$PGDATA/postmaster.pid" "$PGDATA/postmaster.opts" 2>/dev/null || true
fi

echo "[PG-SERVER] Starting Postgres on ${LEADER_IP}:${PGPORT}"
pg_ctl -D "$PGDATA" \
  -o "-p ${PGPORT} \
      -c listen_addresses='${LEADER_IP}' \
      -c hba_file='${HBA_FILE}' \
      -c password_encryption=scram-sha-256" \
  -l "$PGLOG" start

# Record host/port markers only after successful start
echo "$LEADER_IP" > "$MARK_HOST_FILE"
echo "${PGPORT}"  > "$MARK_PORT_FILE"
chmod 600 "$MARK_HOST_FILE" "$MARK_PORT_FILE" 2>/dev/null || true

# ------------------------------------------------------------------------------
# 7) Readiness check (connect to ADMIN_DB)
# ------------------------------------------------------------------------------
echo "[PG-SERVER] Waiting for Postgres to accept connections..."
ready=0
for i in {1..30}; do
  echo "[PG-SERVER] Readiness attempt ${i}..."
  if psql_ok "$LEADER_IP" "$PGPORT" "$ADMIN_DB" "$ADMIN_USER"; then
    ready=1
    break
  fi
  sleep 1
done

if [[ "$ready" -ne 1 ]]; then
  echo "[ERROR] Postgres failed readiness check. Tail of log:"
  tail -n 80 "$PGLOG" || true
  exit 1
fi

echo "[PG-SERVER] Postgres is UP"

# ------------------------------------------------------------------------------
# 8) Ensure primary database exists
# ------------------------------------------------------------------------------
echo "[PG-SERVER] Ensuring DB '${DB_NAME}' exists..."
DB_EXISTS="$(
  psql -w "host=${LEADER_IP} port=${PGPORT} dbname=${ADMIN_DB} user=${ADMIN_USER}" \
       -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}';" \
  | tr -d '[:space:]' || true
)"

if [[ "$DB_EXISTS" != "1" ]]; then
  echo "[PG-SERVER] Creating DB '${DB_NAME}'"
  psql -w "host=${LEADER_IP} port=${PGPORT} dbname=${ADMIN_DB} user=${ADMIN_USER}" \
       -v ON_ERROR_STOP=1 -c "CREATE DATABASE \"${DB_NAME}\";"
else
  echo "[PG-SERVER] Database '${DB_NAME}' already exists"
fi

# ------------------------------------------------------------------------------
# 9) Ensure schemas exist
# ------------------------------------------------------------------------------
echo "[PG-SERVER] Ensuring schemas exist in '${DB_NAME}'"
psql -w "host=${LEADER_IP} port=${PGPORT} dbname=${DB_NAME} user=${ADMIN_USER}" \
     -v ON_ERROR_STOP=1 <<'SQL'
CREATE SCHEMA IF NOT EXISTS source;
CREATE SCHEMA IF NOT EXISTS processed;
CREATE SCHEMA IF NOT EXISTS release;
CREATE SCHEMA IF NOT EXISTS logs;
CREATE SCHEMA IF NOT EXISTS registry;
CREATE SCHEMA IF NOT EXISTS report;
CREATE SCHEMA IF NOT EXISTS ops;
SQL
echo "[PG-SERVER] Schemas ensured."

# ------------------------------------------------------------------------------
# 10) Write connection coordinates
# ------------------------------------------------------------------------------
write_coords "$LEADER_IP" "$PGPORT"

# ------------------------------------------------------------------------------
# 11) Graceful shutdown handler + keep alive
# ------------------------------------------------------------------------------
echo "[PG-SERVER] Server running."
echo "[PG-SERVER] Connect from elsewhere (within allocation) with:"
echo "  source ${COORD_FILE}"
echo "  psql -h ${LEADER_IP} -p ${PGPORT} -d ${DB_NAME} -U ${ADMIN_USER}"

sleep infinity
