#!/usr/bin/env bash
#SBATCH --job-name=pg_server_agir
#SBATCH --account=dash_agir
#SBATCH --partition=compute          # adjust if needed
#SBATCH --time=12:00:00
#SBATCH --cpus-per-task=2
#SBATCH --mem=8G
#SBATCH --output=/project/dash_agir/logs/pg_server/agir_%x_%j.out.log
#SBATCH --error=/project/dash_agir/logs/pg_server/agir_%x_%j.err.log

set -euo pipefail
unset PGHOST PGDATABASE PGUSER PGPASSWORD PGPORT
echo "[PG-SERVER] Starting on $(hostname -f) at $(date)"

# ------------------------------------------------------------------------------
# 1. Activate env / load PostgreSQL
# ------------------------------------------------------------------------------

# Your existing env with tools, etc.
module load miniconda
source activate /project/dash_agir/matthew.kutugata/software/miniforge3/envs/semif_prep

# PostgreSQL binaries (initdb, pg_ctl, psql)
module load postgresql

# ------------------------------------------------------------------------------
# 2. Static config (edit these as needed)
# ------------------------------------------------------------------------------

LOG_DIR="/project/dash_agir/logs"
PG_ROOT="/project/dash_agir/postgres"
mkdir -p "$LOG_DIR" "$PG_ROOT"

# Postgres cluster data directory (persists on /project)
export PGDATA="${PG_ROOT}/pgdata_agir"

# Primary database name
DB_NAME="agir"

# Connection info file (no secrets)
COORD_FILE="${PG_ROOT}/pg_coords.env"


# ------------------------------------------------------------------------------
# 3. Sanity check: required binaries
# ------------------------------------------------------------------------------

for bin in initdb pg_ctl psql; do
  if ! command -v "$bin" >/dev/null 2>&1; then
    echo "[ERROR] Missing binary: $bin (check env / module load postgresql)"
    exit 1
  fi
done

# ------------------------------------------------------------------------------
# 4. Initialize PGDATA if missing (cluster bootstrap)
# ------------------------------------------------------------------------------

if [[ ! -d "$PGDATA" || ! -f "$PGDATA/PG_VERSION" ]]; then
  echo "[PG-SERVER] Initializing new Postgres cluster at $PGDATA"
  mkdir -p "$PGDATA"
  initdb -D "$PGDATA" --encoding=UTF8 --no-locale

  # Listen on all interfaces so other nodes in the cluster can reach it
  {
    echo ""
    echo "# Added by db_server.sh"
    echo "listen_addresses = '*'"
  } >> "$PGDATA/postgresql.conf"

  # Authentication policy:
  #   - local (Unix socket): trust (for bootstrap/admin from this node)
  #   - TCP: md5 (password required)
  cat > "$PGDATA/pg_hba.conf" <<'EOF'
# pg_hba.conf generated by db_server.sh

# Local connections (Unix socket) – trusted, used only on the node itself
local   all             all                                     trust

# IPv4 local loopback
host    all             all             127.0.0.1/32            md5

# IPv6 local loopback
host    all             all             ::1/128                 md5

# IPv4: require password for all DBs/users
host    all             all             0.0.0.0/0               md5

# IPv6: require password for all DBs/users
host    all             all             ::/0                    md5
EOF

  echo "[PG-SERVER] Cluster initialized with md5 password auth for TCP."
else
  echo "[PG-SERVER] Using existing cluster at $PGDATA"
fi

# ------------------------------------------------------------------------------
# 5. Start Postgres on a high, random port
# ------------------------------------------------------------------------------

export PGPORT=$(( 50000 + RANDOM % 1000 ))
PGLOG="${PGDATA}/postgres.log"

echo "[PG-SERVER] Starting Postgres on port $PGPORT"
pg_ctl -D "$PGDATA" -o "-p ${PGPORT}" -l "$PGLOG" start
PGHOST_FQDN="$(hostname -f)"


echo "[PG-SERVER] Waiting for Postgres to accept connections on ${PGHOST_FQDN}:${PGPORT}..."
ready=0
for i in {1..30}; do
  echo "[PG-SERVER] Readiness attempt ${i}..."
  if psql "host=${PGHOST_FQDN} port=${PGPORT} dbname=$DB_NAME user=$USER" \
       -c "SELECT 1;" ; then
    echo "[PG-SERVER] Postgres is UP"
    ready=1
    break
  else
    status=$?
    echo "[PG-SERVER] psql readiness failed with status ${status}"
  fi
  sleep 1
done

if [[ "$ready" -ne 1 ]]; then
  echo "[ERROR] Postgres failed readiness check. Tail of log:"
  tail -n 50 "$PGLOG" || true
  exit 1
fi


# ------------------------------------------------------------------------------
# 6. Do NOT change password — you already set it manually.
#    Just update ~/.pgpass so the client knows how to connect.
# ------------------------------------------------------------------------------

PGPASS_FILE="${HOME}/.pgpass"

# Extract your already-set password from existing .pgpass entry
DB_PASSWORD="$(grep ":${DB_NAME}:${USER}:" "$PGPASS_FILE" | awk -F: '{print $5}')"

# if [[ -z "$DB_PASSWORD" ]]; then
#   echo "[ERROR] Could not find an existing password for ${USER} in ~/.pgpass"
#   echo "        Add it manually in this format:"
#   echo "        host:port:${DB_NAME}:${USER}:password"
#   exit 1
# fi

# # Build new entry for THIS session (new port each time)
# NEW_PG_LINE="${PGHOST_FQDN}:${PGPORT}:${DB_NAME}:${USER}:${DB_PASSWORD}"

# echo "[PG-SERVER] Updating ~/.pgpass for this host/port:"
# echo "  ${PGHOST_FQDN}:${PGPORT}:${DB_NAME}:${USER}:********"

# # Remove old entries for this host/db/user
# grep -v "^${PGHOST_FQDN}:" "$PGPASS_FILE" > "${PGPASS_FILE}.tmp" || true
# mv "${PGPASS_FILE}.tmp" "$PGPASS_FILE"

# # Add new one
# echo "$NEW_PG_LINE" >> "$PGPASS_FILE"
# chmod 600 "$PGPASS_FILE"


# ------------------------------------------------------------------------------
# 7. Ensure primary database exists
# ------------------------------------------------------------------------------

echo "[PG-SERVER] Ensuring DB '${DB_NAME}' exists..."

DB_EXISTS=$(
  psql "host=${PGHOST_FQDN} port=${PGPORT} dbname=${DB_NAME} user=$USER" \
       -tc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}';" \
  | tr -d '[:space:]' || true
)

if [[ "$DB_EXISTS" != "1" ]]; then
  echo "[PG-SERVER] Creating DB '${DB_NAME}'"
  psql "host=${PGHOST_FQDN} port=${PGPORT} dbname=${DB_NAME} user=$USER" \
       -c "CREATE DATABASE ${DB_NAME};"
else
  echo "[PG-SERVER] Database '${DB_NAME}' already exists"
fi


# ------------------------------------------------------------------------------
# 8. Ensure schemas: source / processed / release
# ------------------------------------------------------------------------------

echo "[PG-SERVER] Ensuring schemas exist in '${DB_NAME}'"

psql "host=${PGHOST_FQDN} port=${PGPORT} dbname=${DB_NAME} user=$USER" <<'SQL'
CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS source;
CREATE SCHEMA IF NOT EXISTS processed;
CREATE SCHEMA IF NOT EXISTS release;
CREATE SCHEMA IF NOT EXISTS logs;
SQL

echo "[PG-SERVER] Schemas ensured."

# ------------------------------------------------------------------------------
# 9. Update ~/.pgpass for passwordless TCP access
# ------------------------------------------------------------------------------

# PGPASS_FILE="${HOME}/.pgpass"
# PGPASS_LINE="${PGHOST_FQDN}:${PGPORT}:${DB_NAME}:${USER}:${DB_PASSWORD}"

# echo "[PG-SERVER] Updating ~/.pgpass entry:"
# echo "  ${PGHOST_FQDN}:${PGPORT}:${DB_NAME}:${USER}:********"

# # Remove any stale line for this exact host:port:db:user
# if [[ -f "$PGPASS_FILE" ]]; then
#   grep -v "^${PGHOST_FQDN}:${PGPORT}:${DB_NAME}:${USER}:" "$PGPASS_FILE" > "${PGPASS_FILE}.tmp" || true
#   mv "${PGPASS_FILE}.tmp" "$PGPASS_FILE"
# fi

# echo "$PGPASS_LINE" >> "$PGPASS_FILE"
# chmod 600 "$PGPASS_FILE"

# ------------------------------------------------------------------------------
# 10. Write connection coordinates (no secrets)
# ------------------------------------------------------------------------------

cat > "$COORD_FILE" <<EOF
# Auto-generated by db_server.sh at $(date)
export PGHOST=${PGHOST_FQDN}
export PGPORT=${PGPORT}
export PGDATABASE=${DB_NAME}
export PGUSER=${USER}
# Authentication:
#   - Password is managed by PostgreSQL and stored once in ~/.pgpass
EOF

chmod 600 "$COORD_FILE" || true

echo "[PG-SERVER] Wrote connection info to ${COORD_FILE}:"
cat "$COORD_FILE"

# ------------------------------------------------------------------------------
# 11. Graceful shutdown handler
# ------------------------------------------------------------------------------

cleanup() {
  echo "[PG-SERVER] Shutting down Postgres..."
  pg_ctl -D "$PGDATA" stop -m fast || true
}
trap cleanup EXIT INT TERM

# ------------------------------------------------------------------------------
# 12. Keep server alive for the duration of the job
# ------------------------------------------------------------------------------

echo "[PG-SERVER] Server running."
echo "[PG-SERVER] From another shell (login node / VS Code), you can run:"
echo "  psql -h ${PGHOST_FQDN} -p ${PGPORT} -d ${DB_NAME} -U ${USER}"
echo "If ~/.pgpass is in place (it is), you won't be prompted for a password."

sleep infinity

echo "[DAILY] Scheduling next run for day from now at the same time..."
sbatch --begin=now+1days "$0"