#!/usr/bin/env python3
"""
# scripts/admin/dashboard.py

Local operator dashboard for the AgIR pipeline: per-stage run/lease/staging
state, live Slurm jobs, per-batch lookup, and a trigger that sbatches the
same stage_inputs -> poll_stage_inputs -> submit chain as run.sh and the
scripts/job/run_*_group.sbatch runners. It also covers runbook step 10:
result_syncs state, sync_atlas_results.py (preview locally, run via sbatch,
optional --reopen-run-id), and publish_ceres_db_snapshot.py (check/publish).

Standard library plus pyyaml. From your own machine, one command logs in,
forwards the port and starts it on the login node (Ctrl-C stops it):

    ssh -t -L 8765:localhost:8765 <user>@ceres.scinet.usda.gov <repo>/.venv/bin/python <repo>/scripts/admin/dashboard.py

then open http://localhost:8765/ (first time: the printed URL with ?token=).
scripts/admin/dashboard.sbatch runs it as a Slurm job behind Open OnDemand instead.

The server binds to 127.0.0.1, but login nodes are shared, so every request
must carry the random token printed at startup. Open the printed URL or paste
the token into the login form; either way it's then kept in a cookie.

Readiness views (v_batches_needing_*) take 25-110 s each against the shared
DB, so they're computed in a background thread, cached to
logs/dashboard/readiness_cache.json, and only refreshed on demand. Everything
else (stage_runs, stage_leases, staged_inputs, squeue) is cheap and read live.
"""

import argparse
import html
import json
import logging
import os
import re
import secrets
import signal
import socket
import subprocess
import sys
import threading
import time
import uuid
from datetime import datetime, timedelta, timezone
from http.cookies import SimpleCookie
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import yaml

from orchestrator.sqlite_db import open_db

logger = logging.getLogger("dashboard")

DEFAULT_DB = "/project/dash_agir/globus_index/globus_file_index.sqlite3"
DASH_DIR = REPO_ROOT / "logs" / "dashboard"
READINESS_CACHE = DASH_DIR / "readiness_cache.json"
LOG_READ_ROOTS = (Path("/project/dash_agir"), Path("/90daydata/dash_agir"))
TOKEN_COOKIE = "agir_dash_token"
TOKEN_FILE = Path.home() / ".agir_dashboard_token"
STATE_FILE = Path.home() / ".agir_dashboard.json"
RUN_ID_RE = re.compile(r"^[0-9a-fA-F-]{36}$")
BATCH_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]*$")

# cluster: where submit.py has to run (Atlas configs render Atlas sbatch
# scripts, so those stages can only be viewed from Ceres). site: default
# --site passed to stage_inputs/submit, matching run.sh and the group runners.
STAGES = {
    "raw_to_jpg": {
        "config": "configs/config.raw_to_jpg.example.yaml",
        "cluster": "ceres",
        "site": "JUNO",
    },
    "jpg_to_det": {
        "config": "configs/config.jpg_to_det.atlas.example.yaml",
        "cluster": "atlas",
        "site": "JUNO",
    },
    "det_to_world": {
        "config": "configs/config.det_to_world.example.yaml",
        "cluster": "ceres",
        "site": "CERES",
    },
    "det_to_seg": {
        "config": "configs/config.det_to_seg.atlas.example.yaml",
        "cluster": "atlas",
        "site": "ATLAS",
    },
    "seg_to_cut": {
        "config": "configs/config.seg_to_cut.ceres.example.yaml",
        "cluster": "ceres",
        "site": "CERES",
    },
}
# stage_inputs.py only accepts --rerun for det_to_world.
RERUN_STAGES = {"det_to_world"}

SYNC_CONFIG = "configs/config.result_sync.ceres.example.yaml"
SYNC_STATES = ("requested", "transferring", "transferred", "verified", "ingested",
               "failed", "canceled")

SBATCH_HEADER = """#!/usr/bin/env bash
#SBATCH --job-name=dash_{name}
#SBATCH --account=dash_agir
#SBATCH --partition=compute
#SBATCH --cpus-per-task={cpus}
#SBATCH --mem={mem}
#SBATCH --time={time}
#SBATCH --output={log}
#SBATCH --error={log}

# Generated by scripts/admin/dashboard.py at {created}.
set -uo pipefail
umask 002
cd {repo} || exit 1
source .venv/bin/activate || exit 1
"""

# No `set -e`: stage_inputs/poll exit 1 if *any* batch in the list fails
# staging, which shouldn't block the rest. submit.py only submits batches
# whose staged_inputs rows are completed, so continuing is safe.
STAGE_CHAIN_BODY = """
echo "== stage_inputs $(date --iso-8601=seconds)"
python scripts/job/stage_inputs.py --stage {stage} --config {config} \\
    --batches {batches} --site {site} --limit {limit} \\
    --requested-by dashboard{rerun}
echo "stage_inputs exit=$?"

echo "== poll_stage_inputs $(date --iso-8601=seconds)"
python scripts/job/poll_stage_inputs.py --stage {stage} --config {config} \\
    --wait --interval 60 --limit {poll_limit}
echo "poll_stage_inputs exit=$?"

echo "== submit $(date --iso-8601=seconds)"
python scripts/job/submit.py --stage {stage} --config {config} \\
    --batches {batches} --site {site} --limit {limit}
rc=$?
echo "submit exit=${{rc}}"
echo "== done $(date --iso-8601=seconds)"
exit "${{rc}}"
"""

# Exit 124 means the Globus poll timed out; rerunning resumes the same task.
COMMAND_BODY = """
echo "== {label} $(date --iso-8601=seconds)"
{command}
rc=$?
echo "{label} exit=${{rc}}"
exit "${{rc}}"
"""


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def this_cluster() -> str:
    host = socket.getfqdn().lower()
    for name in ("atlas", "ceres"):
        if name in host:
            return name
    return host


# ---------------------------------------------------------------------------
# SQLite reads
# ---------------------------------------------------------------------------

class Store:
    def __init__(self, db_path: str):
        self.db_path = db_path
        self.lock = threading.Lock()
        self.readiness = self._load_cache()
        self.refreshing = False
        # In-memory preview/trigger tasks: id -> dict.
        self.tasks: dict[str, dict] = {}

    def connect(self):
        conn = open_db(self.db_path, readonly=True)
        # The indexer and ingest jobs write to this DB; wait instead of
        # failing with "database is locked".
        conn.execute("PRAGMA busy_timeout = 60000")
        return conn

    def query(self, sql: str, params=()) -> list[dict]:
        conn = self.connect()
        try:
            return [dict(r) for r in conn.execute(sql, params).fetchall()]
        finally:
            conn.close()

    # -- readiness cache ----------------------------------------------------

    def _load_cache(self) -> dict:
        try:
            cache = json.loads(READINESS_CACHE.read_text())
        except (OSError, ValueError):
            return {}
        # A refresh interrupted by a restart leaves this set.
        for entry in cache.values():
            entry["computing"] = False
        return cache

    def _save_cache(self) -> None:
        DASH_DIR.mkdir(parents=True, exist_ok=True)
        tmp = READINESS_CACHE.with_suffix(".tmp")
        tmp.write_text(json.dumps(self.readiness, indent=1))
        tmp.replace(READINESS_CACHE)

    def refresh_readiness(self, stages=None) -> bool:
        with self.lock:
            if self.refreshing:
                return False
            self.refreshing = True
        threading.Thread(
            target=self._refresh_worker, args=(list(stages or STAGES),), daemon=True
        ).start()
        return True

    def _refresh_worker(self, stages: list[str]) -> None:
        try:
            for stage in stages:
                entry = self.readiness.setdefault(stage, {})
                entry["computing"] = True
                t0 = time.monotonic()
                try:
                    rows = self.query(f"SELECT batch_id FROM v_batches_needing_{stage}")
                    entry.update(
                        batch_ids=sorted({r["batch_id"] for r in rows}),
                        error=None,
                        computed_at=utc_now(),
                        seconds=round(time.monotonic() - t0, 1),
                    )
                except Exception as exc:  # keep the previous list on failure
                    logger.warning("Readiness for %s failed: %s", stage, exc)
                    entry["error"] = str(exc)
                finally:
                    entry["computing"] = False
                    self._save_cache()
        finally:
            self.refreshing = False

    # -- live state -----------------------------------------------------------

    def overview(self) -> dict:
        runs = self.query(
            "SELECT stage, status, COUNT(*) AS n, MAX(ended_at) AS last_ended "
            "FROM stage_runs GROUP BY stage, status"
        )
        leases = self.query(
            "SELECT stage, "
            "SUM(expires_at > strftime('%Y-%m-%dT%H:%M:%SZ','now')) AS active, "
            "SUM(expires_at <= strftime('%Y-%m-%dT%H:%M:%SZ','now')) AS expired "
            "FROM stage_leases GROUP BY stage"
        )
        staging = self.query(
            "SELECT stage, status, COUNT(DISTINCT batch_id) AS n "
            "FROM staged_inputs GROUP BY stage, status"
        )
        out = {}
        here = this_cluster()
        for stage, spec in STAGES.items():
            ready = self.readiness.get(stage, {})
            out[stage] = {
                "cluster": spec["cluster"],
                "site": spec["site"],
                "config": spec["config"],
                "triggerable": spec["cluster"] == here,
                "rerun": stage in RERUN_STAGES,
                "runs": {r["status"]: r["n"] for r in runs if r["stage"] == stage},
                "last_run": max(
                    (r["last_ended"] for r in runs if r["stage"] == stage), default=None
                ),
                "leases": next(
                    ({"active": ls["active"] or 0, "expired": ls["expired"] or 0}
                     for ls in leases if ls["stage"] == stage),
                    {"active": 0, "expired": 0},
                ),
                "staging": {s["status"]: s["n"] for s in staging if s["stage"] == stage},
                "ready": {
                    "count": len(ready.get("batch_ids", [])) if "batch_ids" in ready else None,
                    "batch_ids": ready.get("batch_ids", []),
                    "computed_at": ready.get("computed_at"),
                    "computing": ready.get("computing", False),
                    "seconds": ready.get("seconds"),
                    "error": ready.get("error"),
                },
            }
        return {"stages": out, "cluster": here, "refreshing": self.refreshing}

    def activity(self) -> dict:
        now_sql = "strftime('%Y-%m-%dT%H:%M:%SZ','now')"
        return {
            "recent_runs": self.query(
                "SELECT run_id, batch_id, stage, status, exit_code, started_at, ended_at, "
                "duration_ms, n_units_discovered, n_units_succeeded, n_units_failed, run_root "
                "FROM stage_runs ORDER BY ended_at DESC LIMIT 40"
            ),
            "leases": self.query(
                f"SELECT batch_id, stage, orchestrator_id, claimed_at, expires_at, slurm_job_id, "
                f"expires_at > {now_sql} AS active "
                f"FROM stage_leases ORDER BY claimed_at DESC"
            ),
            "staging": self.query(
                "SELECT batch_id, stage, status, globus_task_id, error_summary, updated_at "
                "FROM staged_inputs "
                "WHERE status NOT IN ('completed', 'canceled') "
                "ORDER BY updated_at DESC LIMIT 100"
            ),
            "jobs": squeue_jobs(),
            "tasks": sorted(
                ({k: v for k, v in t.items() if k != "output"} for t in self.tasks.values()),
                key=lambda t: t["created"],
                reverse=True,
            ),
        }

    def sync_state(self) -> dict:
        try:
            cfg = yaml.safe_load((REPO_ROOT / SYNC_CONFIG).read_text())
            inbox = Path(cfg["result_sync"]["ceres_inbox"])
            snapshot = Path(cfg["snapshot"]["ceres_publish_path"])
        except (OSError, KeyError, TypeError, yaml.YAMLError) as exc:
            return {"error": f"Can't read {SYNC_CONFIG}: {exc}"}

        known = {r["run_id"] for r in self.query("SELECT run_id FROM result_syncs")}
        try:
            inbox_ids = [f.name.split(".", 1)[0] for f in inbox.glob("*.result-sync.json")]
        except OSError:
            inbox_ids = []
        try:
            st = snapshot.stat()
            snap = {"path": str(snapshot), "mtime": datetime.fromtimestamp(
                st.st_mtime, timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"), "size": st.st_size}
        except OSError:
            snap = {"path": str(snapshot), "mtime": None, "size": None}

        return {
            "config": SYNC_CONFIG,
            "states": SYNC_STATES,
            "counts": self.query(
                "SELECT stage, status, COUNT(*) AS n FROM result_syncs GROUP BY stage, status"
            ),
            "outstanding": self.query(
                "SELECT run_id, batch_id, stage, run_status, status, attempt_count, "
                "globus_task_id, error_summary, updated_at FROM result_syncs "
                "WHERE status != 'ingested' ORDER BY updated_at DESC LIMIT 200"
            ),
            "recent": self.query(
                "SELECT run_id, batch_id, stage, run_status, promotion_succeeded, ingested_at "
                "FROM result_syncs WHERE status = 'ingested' "
                "ORDER BY ingested_at DESC LIMIT 25"
            ),
            "inbox": {"path": str(inbox), "files": len(inbox_ids),
                      "unregistered": sorted(set(inbox_ids) - known)},
            "snapshot": snap,
        }

    def batch(self, batch_id: str) -> dict:
        p = (batch_id,)
        return {
            "batch_id": batch_id,
            "runs": self.query(
                "SELECT run_id, stage, status, exit_code, started_at, ended_at, duration_ms, "
                "n_units_discovered, n_units_succeeded, n_units_failed, run_root, logs_path "
                "FROM stage_runs WHERE batch_id = ? ORDER BY ended_at DESC",
                p,
            ),
            "leases": self.query("SELECT * FROM stage_leases WHERE batch_id = ?", p),
            "staging": self.query(
                "SELECT stage, status, src_path, dst_path, globus_task_id, error_summary, "
                "updated_at FROM staged_inputs WHERE batch_id = ? ORDER BY updated_at DESC",
                p,
            ),
            "syncs": self.query(
                "SELECT run_id, stage, status, run_status, error_summary, updated_at "
                "FROM result_syncs WHERE batch_id = ? ORDER BY updated_at DESC",
                p,
            ),
            "ready_for": [
                s for s, e in self.readiness.items() if batch_id in e.get("batch_ids", [])
            ],
        }


def squeue_jobs() -> list[dict]:
    fields = ["job_id", "name", "state", "time", "start", "reason", "partition", "stdout"]
    try:
        out = subprocess.run(
            ["squeue", "-u", os.environ.get("USER", ""), "-h", "-O",
             "JobID:|,Name:|,State:|,TimeUsed:|,StartTime:|,Reason:|,Partition:|,STDOUT:"],
            capture_output=True, text=True, timeout=20, check=True,
        ).stdout
    except (OSError, subprocess.SubprocessError) as exc:
        return [{"error": str(exc)}]
    jobs = []
    for line in out.splitlines():
        parts = [p.strip() for p in line.split("|")]
        if len(parts) < len(fields):
            continue
        job = dict(zip(fields, parts))
        job["stdout"] = expand_slurm_path(job["stdout"], job["job_id"], job["name"])
        jobs.append(job)
    return jobs


def expand_slurm_path(path: str, job_id: str, name: str) -> str:
    """Fill in the sbatch --output/--error placeholders the dashboard sees."""
    array_job, _, array_task = job_id.partition("_")
    return (path.replace("%j", job_id).replace("%x", name)
            .replace("%u", os.environ.get("USER", ""))
            .replace("%A", array_job).replace("%a", array_task))


def sacct_history(hours: int = 48) -> list[dict]:
    """The user's jobs (not steps) that started or ran in the last `hours`."""
    fields = ["job_id", "job_id_raw", "name", "state", "start", "end", "elapsed",
              "exit_code", "nodes", "stdout", "stderr"]
    since = (datetime.now() - timedelta(hours=hours)).strftime("%Y-%m-%dT%H:%M:%S")
    try:
        out = subprocess.run(
            ["sacct", "-u", os.environ.get("USER", ""), "-X", "-n", "--parsable2",
             "--starttime", since,
             "-o", "JobID,JobIDRaw,JobName,State,Start,End,Elapsed,ExitCode,NodeList,"
                   "StdOut,StdErr"],
            capture_output=True, text=True, timeout=30, check=True,
        ).stdout
    except (OSError, subprocess.SubprocessError) as exc:
        return [{"error": str(exc)}]
    jobs = []
    for line in out.splitlines():
        parts = line.split("|")
        if len(parts) != len(fields):
            continue
        job = dict(zip(fields, parts))
        # Never started (still queued, or cancelled while pending).
        if job["state"] == "PENDING" or job["start"] in ("None", "Unknown", ""):
            continue
        # "CANCELLED by 12345" -> CANCELLED, so the state filter/colour works.
        job["state"] = job["state"].split()[0]
        for key in ("stdout", "stderr"):
            path = expand_slurm_path(job[key], job["job_id"], job["name"])
            # Only link logs that exist (rotated/deleted ones would just error).
            job[key] = path if path and os.path.isfile(path) else ""
        jobs.append(job)
    jobs.sort(key=lambda j: j["start"], reverse=True)
    return jobs


def read_log_tail(path: str, lines: int = 300) -> str:
    p = Path(path).resolve()
    if not any(p.is_relative_to(root) for root in LOG_READ_ROOTS):
        raise PermissionError(f"Refusing to read outside {', '.join(map(str, LOG_READ_ROOTS))}")
    with p.open("rb") as fh:
        fh.seek(0, os.SEEK_END)
        size = fh.tell()
        fh.seek(max(0, size - 256 * 1024))
        data = fh.read().decode("utf-8", errors="replace")
    return "\n".join(data.splitlines()[-lines:])


# ---------------------------------------------------------------------------
# Preview / trigger
# ---------------------------------------------------------------------------

def parse_batch_ids(text: str) -> list[str]:
    ids = []
    for token in re.split(r"[\s,]+", text or ""):
        token = token.strip()
        if not token or token.startswith("#"):
            continue
        if not BATCH_ID_RE.match(token):
            raise ValueError(f"Invalid batch id: {token!r}")
        if token not in ids:
            ids.append(token)
    if not ids:
        raise ValueError("No batch ids given")
    return ids


def write_batch_file(stage: str, batch_ids: list[str], stamp: str) -> Path:
    DASH_DIR.mkdir(parents=True, exist_ok=True)
    path = DASH_DIR / f"{stage}_{stamp}.batches.txt"
    path.write_text("".join(f"{b}\n" for b in batch_ids))
    return path


def _new_task(store: Store, kind: str, stage: str, items: list[str]) -> dict:
    task = {
        "id": uuid.uuid4().hex[:10], "kind": kind, "stage": stage, "batches": items,
        "status": "running", "created": utc_now(), "batch_file": None,
        "output": "", "job_id": None, "log": None,
        "stamp": datetime.now().strftime("%Y%m%d_%H%M%S"),
    }
    store.tasks[task["id"]] = task
    return task


def _start_local(task: dict, cmd: list[str]) -> str:
    threading.Thread(target=_run_preview, args=(task, cmd), daemon=True).start()
    return task["id"]


def _sbatch(task: dict, name: str, body: str, *, time_limit: str,
            cpus: int = 1, mem: str = "2G") -> str:
    if this_cluster() != "ceres":
        task.update(status="error", output=f"{name} must be submitted from ceres")
        return task["id"]
    base = DASH_DIR / f"{name}_{task['stamp']}_{task['id']}"
    log = f"{base}_%j.out"
    script = base.with_suffix(".sbatch")
    DASH_DIR.mkdir(parents=True, exist_ok=True)
    script.write_text(SBATCH_HEADER.format(
        name=name, cpus=cpus, mem=mem, time=time_limit, log=log,
        created=utc_now(), repo=REPO_ROOT,
    ) + body)
    try:
        proc = subprocess.run(
            ["sbatch", "--parsable", str(script)],
            cwd=REPO_ROOT, capture_output=True, text=True, timeout=60,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        task.update(status="error", output=str(exc))
        return task["id"]
    if proc.returncode != 0:
        task.update(status="error", output=proc.stderr or proc.stdout)
        return task["id"]
    job_id = proc.stdout.strip().split(";")[0]
    task.update(
        status="submitted", job_id=job_id, output=f"Submitted {script}\nSlurm job {job_id}",
        log=log.replace("%j", job_id),
    )
    logger.info("Submitted %s (%d item(s)): job %s", name, len(task["batches"]), job_id)
    return task["id"]


def run_task(store: Store, kind: str, stage: str, batch_ids: list[str], opts: dict) -> str:
    spec = STAGES[stage]
    task = _new_task(store, kind, stage, batch_ids)
    batch_file = write_batch_file(stage, batch_ids, f"{task['stamp']}_{task['id']}")
    task["batch_file"] = str(batch_file)
    site = opts.get("site") or spec["site"]
    rerun = bool(opts.get("rerun")) and stage in RERUN_STAGES

    if kind == "preview":
        return _start_local(task, [
            sys.executable, "scripts/job/stage_inputs.py", "--stage", stage,
            "--config", spec["config"], "--batches", str(batch_file), "--site", site,
            "--limit", str(max(50, len(batch_ids))), "--dry-run",
        ] + (["--rerun"] if rerun else []))

    if spec["cluster"] != this_cluster():
        task.update(status="error", output=f"{stage} must be submitted from {spec['cluster']}")
        return task["id"]
    return _sbatch(task, stage, STAGE_CHAIN_BODY.format(
        stage=stage, config=spec["config"], batches=batch_file, site=site,
        limit=max(50, len(batch_ids)), poll_limit=max(200, 10 * len(batch_ids)),
        rerun=" \\\n    --rerun" if rerun else "",
    ), time_limit=opts.get("time") or "12:00:00")


def run_sync_task(store: Store, action: str, opts: dict) -> str:
    """Preview/run sync_atlas_results.py, or check/publish the DB snapshot."""
    if action in ("sync_preview", "sync_run"):
        reopen = [r for r in opts.get("reopen", []) if RUN_ID_RE.match(r)]
        args = ["scripts/admin/sync_atlas_results.py", "--config", SYNC_CONFIG,
                "--bundle-limit", str(int(opts.get("bundle_limit") or 50))]
        if opts.get("refresh_inventory"):
            args.append("--refresh-inventory")
        task = _new_task(store, "preview" if action == "sync_preview" else "trigger",
                         "result_sync", reopen)
        if action == "sync_preview":
            # --reopen-run-id writes to SQLite, so it's never part of a dry run.
            return _start_local(task, [sys.executable, *args, "--dry-run"])
        for run_id in reopen:
            args += ["--reopen-run-id", run_id]
        # The inventory refresh after a promotion walks all of
        # semifield-developed-images with config'd max_workers.
        return _sbatch(task, "result_sync", COMMAND_BODY.format(
            label="sync_atlas_results", command="python " + " ".join(args),
        ), time_limit="6:00:00", cpus=8, mem="16G")

    if action in ("snapshot_check", "snapshot_publish"):
        args = ["scripts/admin/publish_ceres_db_snapshot.py", "--config", SYNC_CONFIG]
        task = _new_task(store, "check" if action == "snapshot_check" else "trigger",
                         "db_snapshot", [])
        # Even --dry-run backs up the full (~28 GB) DB to a candidate file
        # before reconciling, so both variants go to Slurm, not the login node.
        if action == "snapshot_check":
            args.append("--dry-run")
        elif opts.get("transfer"):
            args.append("--transfer")
        return _sbatch(task, "db_snapshot", COMMAND_BODY.format(
            label="publish_ceres_db_snapshot", command="python " + " ".join(args),
        ), time_limit="4:00:00", cpus=2, mem="8G")

    raise ValueError(f"Unknown sync action {action!r}")


def _run_preview(task: dict, cmd: list[str]) -> None:
    try:
        proc = subprocess.run(
            cmd, cwd=REPO_ROOT, capture_output=True, text=True, timeout=900,
        )
        task["output"] = (proc.stdout + proc.stderr)[-200_000:]
        task["status"] = "done" if proc.returncode == 0 else f"exit {proc.returncode}"
    except subprocess.TimeoutExpired:
        task.update(status="timeout", output="Preview exceeded 15 minutes.")
    except OSError as exc:
        task.update(status="error", output=str(exc))


# ---------------------------------------------------------------------------
# HTTP
# ---------------------------------------------------------------------------

def make_handler(store: Store, token: str):
    class Handler(BaseHTTPRequestHandler):
        def log_message(self, fmt, *args):
            logger.debug("%s " + fmt, self.address_string(), *args)

        def _cookie_token(self) -> str:
            cookies = SimpleCookie(self.headers.get("Cookie") or "")
            morsel = cookies.get(TOKEN_COOKIE)
            return morsel.value if morsel else ""

        def _authorized(self, query: dict) -> bool:
            supplied = (
                self.headers.get("X-Token")
                or (query.get("token") or [""])[0]
                or self._cookie_token()
            )
            return secrets.compare_digest(supplied, token)

        def _redirect_with_cookie(self):
            # VS Code port forwarding can drop the query string, so after one
            # authorized visit the token rides along in a cookie instead.
            self.send_response(303)
            self.send_header(
                "Set-Cookie",
                f"{TOKEN_COOKIE}={token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=2592000",
            )
            self.send_header("Location", "./")
            self.send_header("Content-Length", "0")
            self.end_headers()

        def _send(self, code: int, body, ctype="application/json"):
            if not isinstance(body, (bytes, str)):
                body = json.dumps(body, default=str)
            if isinstance(body, str):
                body = body.encode()
            self.send_response(code)
            self.send_header("Content-Type", f"{ctype}; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(body)

        def do_GET(self):
            url = urlparse(self.path)
            q = parse_qs(url.query)
            if not self._authorized(q):
                if url.path == "/":
                    return self._send(403, LOGIN_PAGE, "text/html")
                return self._send(403, {"error": "forbidden"})
            try:
                if url.path == "/" and "token" in q:
                    return self._redirect_with_cookie()
                if url.path == "/":
                    return self._send(200, PAGE.replace("__DB__", html.escape(store.db_path)),
                                      "text/html")
                if url.path == "/api/overview":
                    return self._send(200, store.overview())
                if url.path == "/api/activity":
                    return self._send(200, store.activity())
                if url.path == "/api/batch":
                    return self._send(200, store.batch(parse_batch_ids(q["id"][0])[0]))
                if url.path == "/api/sync":
                    return self._send(200, store.sync_state())
                if url.path == "/api/history":
                    return self._send(200, {"jobs": sacct_history()})
                if url.path == "/api/task":
                    return self._send(200, store.tasks[q["id"][0]])
                if url.path == "/api/log":
                    return self._send(200, {"text": read_log_tail(q["path"][0])})
            except (KeyError, IndexError):
                return self._send(404, {"error": "not found"})
            except (ValueError, PermissionError, OSError) as exc:
                return self._send(400, {"error": str(exc)})
            self._send(404, {"error": "not found"})

        def do_POST(self):
            url = urlparse(self.path)
            if not self._authorized(parse_qs(url.query)):
                return self._send(403, {"error": "forbidden"})
            try:
                length = int(self.headers.get("Content-Length") or 0)
                body = json.loads(self.rfile.read(length) or b"{}")
                if url.path == "/api/refresh":
                    stages = [s for s in body.get("stages", STAGES) if s in STAGES]
                    return self._send(200, {"started": store.refresh_readiness(stages)})
                if url.path == "/api/sync":
                    task_id = run_sync_task(store, body.get("action"), body)
                    return self._send(200, store.tasks[task_id])
                if url.path in ("/api/preview", "/api/trigger"):
                    stage = body.get("stage")
                    if stage not in STAGES:
                        raise ValueError(f"Unknown stage {stage!r}")
                    kind = url.path.rsplit("/", 1)[1]
                    task_id = run_task(
                        store, kind, stage, parse_batch_ids(body.get("batches", "")), body
                    )
                    return self._send(200, store.tasks[task_id])
            except ValueError as exc:
                return self._send(400, {"error": str(exc)})
            self._send(404, {"error": "not found"})

    return Handler


LOGIN_PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AgIR Dashboard Login</title>
<style>
body { font: 14px system-ui, sans-serif; display: grid; place-items: center; min-height: 90vh;
  margin: 0; background: #f6f7f9; color: #1c2330; }
@media (prefers-color-scheme: dark) { body { background: #12161c; color: #e4e8ee; } }
form { display: grid; gap: 10px; width: min(420px, 90vw); }
input, button { font: inherit; padding: 8px 10px; border-radius: 6px; border: 1px solid #8894a6; }
</style></head><body>
<form method="get" action="./">
  <strong>AgIR pipeline dashboard</strong>
  <label>Paste the token printed when the server started
    <input name="token" autocomplete="off" autofocus required></label>
  <button type="submit">Open dashboard</button>
</form></body></html>
"""


PAGE = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AgIR Pipeline Dashboard</title>
<style>
:root {
  --bg: #f6f7f9; --panel: #ffffff; --ink: #1c2330; --muted: #5d6778; --line: #dfe3ea;
  --accent: #2f6f4f; --accent-ink: #ffffff; --ok: #2f7d4f; --warn: #a86a12; --bad: #b3372f;
  --info: #2c5f9e; --chip: #eef1f5; --mono: ui-monospace, SFMono-Regular, Menlo, monospace;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #12161c; --panel: #1a2029; --ink: #e4e8ee; --muted: #98a2b3; --line: #2b3441;
    --accent: #5fb487; --accent-ink: #0d1a13; --ok: #5fb487; --warn: #e0a84a; --bad: #ec7a70;
    --info: #7aa7e0; --chip: #232b36;
  }
}
* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--ink);
  font: 14px/1.45 system-ui, -apple-system, "Segoe UI", sans-serif; }
header { display: flex; align-items: baseline; gap: 16px; flex-wrap: wrap;
  padding: 18px 24px 8px; }
header h1 { font-size: 20px; margin: 0; }
header .meta { color: var(--muted); font-size: 12px; font-family: var(--mono); }
main { padding: 8px 24px 40px; display: grid; gap: 20px; }
h2 { font-size: 15px; margin: 0 0 10px; display: flex; align-items: center; gap: 10px; }
section.panel { background: var(--panel); border: 1px solid var(--line); border-radius: 10px;
  padding: 16px; min-width: 0; }
.cards { display: grid; grid-template-columns: repeat(auto-fill, minmax(230px, 1fr)); gap: 12px; }
.card { border: 1px solid var(--line); border-radius: 8px; padding: 12px; background: var(--panel); }
.card h3 { margin: 0 0 2px; font-size: 14px; font-family: var(--mono); }
.card .sub { color: var(--muted); font-size: 12px; margin-bottom: 8px; }
.big { font-size: 26px; font-weight: 650; font-variant-numeric: tabular-nums; }
.row { display: flex; justify-content: space-between; gap: 8px; font-size: 13px; }
.row span:last-child { font-variant-numeric: tabular-nums; }
.chips { display: flex; flex-wrap: wrap; gap: 4px; margin-top: 6px; }
.chip { background: var(--chip); border-radius: 999px; padding: 1px 8px; font-size: 12px; }
.s-success, .s-completed, .s-done, .s-RUNNING, .s-submitted { color: var(--ok); }
.s-partial_success, .s-PENDING, .s-requested, .s-active, .s-running { color: var(--warn); }
.s-failed, .s-error, .s-canceled, .s-timeout, .s-FAILED { color: var(--bad); }
.grid2 { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); gap: 20px; }
@media (max-width: 1000px) { .grid2 { grid-template-columns: 1fr; } }
table { width: 100%; border-collapse: collapse; font-size: 12.5px; }
th, td { text-align: left; padding: 5px 8px; border-bottom: 1px solid var(--line);
  white-space: nowrap; }
th { color: var(--muted); font-weight: 600; position: sticky; top: 0; background: var(--panel); }
td.mono, .mono { font-family: var(--mono); font-size: 12px; }
.scroll { max-height: 340px; overflow: auto; }
button, select, input, textarea { font: inherit; color: var(--ink); background: var(--panel);
  border: 1px solid var(--line); border-radius: 6px; padding: 6px 10px; }
button { cursor: pointer; }
button.primary { background: var(--accent); color: var(--accent-ink); border-color: var(--accent);
  font-weight: 600; }
button:disabled { opacity: .5; cursor: not-allowed; }
button.link { border: none; background: none; color: var(--info); padding: 0; font-size: 12px; }
textarea { width: 100%; min-height: 110px; font-family: var(--mono); font-size: 12px; }
.form { display: grid; gap: 10px; }
.form .line { display: flex; gap: 10px; flex-wrap: wrap; align-items: center; }
.muted { color: var(--muted); }
.note { font-size: 12px; color: var(--muted); }
.warnbox { border-left: 3px solid var(--warn); padding: 6px 10px; background: var(--chip);
  border-radius: 4px; font-size: 12.5px; }
pre { background: var(--chip); padding: 10px; border-radius: 6px; font-size: 12px; overflow: auto;
  max-height: 420px; white-space: pre-wrap; word-break: break-all; margin: 8px 0 0; }
dialog { width: min(1100px, 94vw); border: 1px solid var(--line); border-radius: 10px;
  background: var(--panel); color: var(--ink); padding: 16px; }
dialog pre { max-height: 70vh; }
.flow { display: flex; flex-wrap: wrap; align-items: center; gap: 6px; margin: 4px 0 12px; }
.flow .st { border: 1px solid var(--line); border-radius: 8px; padding: 6px 10px; min-width: 88px; }
.flow .st .big { font-size: 20px; }
.flow .arrow { color: var(--muted); }
.flow .sep { width: 1px; align-self: stretch; background: var(--line); margin: 0 6px; }
.s-ingested, .s-verified, .s-transferred { color: var(--ok); }
.s-transferring { color: var(--warn); }
.s-COMPLETED { color: var(--ok); }
.s-FAILED, .s-TIMEOUT, .s-OUT_OF_MEMORY, .s-NODE_FAIL, .s-CANCELLED, .s-BOOT_FAIL { color: var(--bad); }
.spin { display: inline-block; width: 10px; height: 10px; border: 2px solid var(--muted);
  border-top-color: transparent; border-radius: 50%; animation: s 1s linear infinite; }
@keyframes s { to { transform: rotate(360deg); } }
@media (max-width: 600px) { header, main { padding-left: 16px; padding-right: 16px; } }
</style>
</head>
<body>
<header>
  <h1>AgIR pipeline</h1>
  <span class="meta">db: __DB__</span>
  <span class="meta" id="cluster"></span>
  <span class="meta" id="updated"></span>
</header>
<main>
  <section class="panel">
    <h2>Stages
      <button id="refreshAll">Refresh readiness</button>
      <span class="note" id="refreshNote">Readiness views take ~25–110 s each; cached between refreshes.</span>
    </h2>
    <div class="cards" id="cards"></div>
  </section>

  <div class="grid2">
    <section class="panel">
      <h2>Trigger stage</h2>
      <div class="form">
        <div class="line">
          <label>Stage <select id="tStage"></select></label>
          <label>Site <input id="tSite" size="7"></label>
          <label id="rerunWrap"><input type="checkbox" id="tRerun"> --rerun</label>
          <button class="link" id="fillReady">Fill with ready batches</button>
        </div>
        <textarea id="tBatches" placeholder="Batch IDs, one per line (e.g. MD_2025-04-25)"></textarea>
        <div class="line">
          <button id="previewBtn">Preview (stage_inputs --dry-run)</button>
          <button class="primary" id="triggerBtn">Submit sbatch chain</button>
          <span class="note" id="tCount"></span>
        </div>
        <div class="note">Submits one Slurm job that runs stage_inputs → poll_stage_inputs --wait → submit
          for these batches. Script, batch file and log go to logs/dashboard/.</div>
        <div id="tStatus"></div>
      </div>
    </section>

    <section class="panel">
      <h2>Batch lookup</h2>
      <div class="line form"><div class="line">
        <input id="bId" placeholder="MD_2025-04-25" size="18">
        <button id="bGo">Look up</button>
      </div></div>
      <div id="bOut" class="note" style="margin-top:10px">Enter a batch ID to see its state in every stage.</div>
    </section>
  </div>

  <section class="panel">
    <h2>Result sync <span class="note">Atlas → Ceres · sync_atlas_results.py · <span id="syConfig" class="mono"></span></span></h2>
    <div id="syFlow" class="flow"></div>
    <div class="note" id="syMeta"></div>
    <div class="grid2" style="margin-top:12px">
      <div class="form">
        <strong>1 · Sync results</strong>
        <div class="line">
          <label>Bundle limit <input id="syLimit" type="number" min="1" value="10" style="width:80px"></label>
          <label><input type="checkbox" id="syRefresh"> --refresh-inventory</label>
        </div>
        <div class="line">
          <button id="syPreview">Preview (--dry-run)</button>
          <button class="primary" id="syRun">Run sync</button>
          <span class="note" id="syReopenNote"></span>
        </div>
        <div class="note">Exit 124 means the Globus poll timed out. Run it again; it resumes the recorded task.
          Tick failed/canceled rows below to include <span class="mono">--reopen-run-id</span>.</div>
      </div>
      <div class="form">
        <strong>2 · Publish DB snapshot</strong>
        <div class="line">
          <button id="snCheck">Check reconciliation (--dry-run, sbatch)</button>
          <button class="primary" id="snPublish">Publish snapshot</button>
          <label><input type="checkbox" id="snTransfer"> --transfer to Atlas</label>
        </div>
        <div class="note">Publish only after Atlas jobs have stopped writing requests and the sync has been run through to the end.
          Don't use --transfer while the external nightly copy is still enabled.</div>
      </div>
    </div>
    <div id="syStatus"></div>
    <div class="grid2" style="margin-top:12px">
      <div><div class="note">Outstanding (not ingested)</div><div class="scroll"><table id="syOut"></table></div></div>
      <div><div class="note">Recently ingested</div><div class="scroll"><table id="syRecent"></table></div></div>
    </div>
  </section>

  <section class="panel">
    <h2>Slurm jobs <span class="note" id="jobCount"></span></h2>
    <div class="scroll"><table id="jobs"></table></div>
  </section>

  <section class="panel">
    <h2>Job history <span class="note">last 48 h, from sacct</span></h2>
    <div class="line form" style="margin-bottom:8px"><div class="line">
      <input id="hName" placeholder="Filter by job name" size="24">
      <select id="hState">
        <option value="">All states</option>
        <option value="bad">Failed / timeout / OOM / cancelled</option>
        <option value="COMPLETED">Completed</option>
        <option value="RUNNING">Running</option>
      </select>
      <span class="chips" id="hSummary"></span>
    </div></div>
    <div class="scroll" style="max-height:420px"><table id="history"></table></div>
  </section>

  <div class="grid2">
    <section class="panel">
      <h2>Dashboard submissions</h2>
      <div class="scroll"><table id="tasks"></table></div>
    </section>
    <section class="panel">
      <h2>Input staging in flight</h2>
      <div class="scroll"><table id="staging"></table></div>
    </section>
  </div>

  <div class="grid2">
    <section class="panel">
      <h2>Recent runs</h2>
      <div class="scroll"><table id="runs"></table></div>
    </section>
    <section class="panel">
      <h2>Leases</h2>
      <div class="scroll"><table id="leases"></table></div>
    </section>
  </div>
</main>

<dialog id="dlg">
  <div style="display:flex;justify-content:space-between;align-items:center;gap:10px">
    <strong id="dlgTitle" class="mono"></strong>
    <span><button id="dlgReload">Reload</button> <button id="dlgClose">Close</button></span>
  </div>
  <pre id="dlgBody"></pre>
</dialog>

<script>
const TOKEN = new URLSearchParams(location.search).get("token") || "";
const H = { "Content-Type": "application/json", ...(TOKEN ? { "X-Token": TOKEN } : {}) };
let OV = null;

async function api(path, body) {
  // Relative, so it resolves under an Open OnDemand /rnode/<host>/<port>/ prefix.
  const r = await fetch(path.replace(/^\//, ""), body === undefined ? { headers: H }
    : { method: "POST", headers: H, body: JSON.stringify(body) });
  const j = await r.json();
  if (!r.ok) throw new Error(j.error || r.statusText);
  return j;
}
const esc = s => String(s ?? "").replace(/[&<>"']/g, c =>
  ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
const st = s => `<span class="s-${esc(s)}">${esc(s)}</span>`;
const ago = iso => {
  if (!iso) return "—";
  const d = (Date.now() - new Date(iso).getTime()) / 1000;
  if (isNaN(d)) return esc(iso);
  if (d < 90) return `${Math.round(d)}s ago`;
  if (d < 5400) return `${Math.round(d / 60)}m ago`;
  if (d < 172800) return `${Math.round(d / 3600)}h ago`;
  return `${Math.round(d / 86400)}d ago`;
};
const dur = ms => ms == null ? "" : ms < 60000 ? `${(ms / 1000).toFixed(0)}s`
  : `${Math.floor(ms / 60000)}m${String(Math.round(ms % 60000 / 1000)).padStart(2, "0")}s`;

function table(el, cols, rows, empty = "Nothing here.") {
  if (!rows.length) { el.innerHTML = `<tr><td class="muted">${empty}</td></tr>`; return; }
  el.innerHTML = "<tr>" + cols.map(c => `<th>${c[0]}</th>`).join("") + "</tr>" +
    rows.map(r => "<tr>" + cols.map(c => `<td class="${c[2] || ""}">${c[1](r)}</td>`).join("") + "</tr>").join("");
}

function logBtn(path, label = "log") {
  return path ? `<button class="link" data-log="${esc(path)}">${label}</button>` : "";
}

async function loadOverview() {
  OV = await api("/api/overview");
  document.getElementById("cluster").textContent = `running on: ${OV.cluster}`;
  const cards = document.getElementById("cards");
  cards.innerHTML = Object.entries(OV.stages).map(([name, s]) => {
    const r = s.ready;
    const readyTxt = r.computing ? `<span class="spin"></span>` : r.count ?? "—";
    const runs = Object.entries(s.runs).map(([k, v]) => `<span class="chip">${st(k)} ${v}</span>`).join("");
    const stg = Object.entries(s.staging).map(([k, v]) => `<span class="chip">${st(k)} ${v}</span>`).join("");
    return `<div class="card">
      <h3>${esc(name)}</h3>
      <div class="sub">${esc(s.cluster)} · site ${esc(s.site)}${s.triggerable ? "" : " · view only here"}</div>
      <div class="row"><span class="muted">Ready to run</span></div>
      <div class="big">${readyTxt}</div>
      <div class="note">${r.error ? `<span class="s-failed">${esc(r.error)}</span>` :
        r.computed_at ? `computed ${ago(r.computed_at)} (${r.seconds}s)` : "not computed yet"}
        · <button class="link" data-refresh="${esc(name)}">refresh</button>
        ${r.count ? ` · <button class="link" data-use="${esc(name)}">use in trigger</button>` : ""}</div>
      <div class="row" style="margin-top:8px"><span class="muted">Leases</span>
        <span>${s.leases.active} active${s.leases.expired ? `, ${s.leases.expired} expired` : ""}</span></div>
      <div class="row"><span class="muted">Last run</span><span>${ago(s.last_run)}</span></div>
      <div class="chips">${runs || '<span class="note">no runs</span>'}</div>
      ${stg ? `<div class="note" style="margin-top:6px">staging (batches)</div><div class="chips">${stg}</div>` : ""}
    </div>`;
  }).join("");
  document.getElementById("refreshAll").disabled = OV.refreshing;
  const sel = document.getElementById("tStage");
  if (!sel.options.length) {
    sel.innerHTML = Object.keys(OV.stages).map(s => `<option>${s}</option>`).join("");
    sel.value = "det_to_world";
    onStage();
  }
  updateTriggerState();
}

async function loadActivity() {
  const a = await api("/api/activity");
  const jobs = a.jobs.filter(j => !j.error);
  document.getElementById("jobCount").textContent =
    `${jobs.filter(j => j.state === "RUNNING").length} running · ${jobs.filter(j => j.state === "PENDING").length} pending`;
  table(document.getElementById("jobs"), [
    ["Job", j => esc(j.job_id), "mono"], ["Name", j => esc(j.name), "mono"],
    ["State", j => st(j.state)], ["Time", j => esc(j.time)], ["Start", j => esc(j.start)],
    ["Reason", j => esc(j.reason)], ["", j => logBtn(j.stdout)],
  ], a.jobs[0]?.error ? [] : jobs, a.jobs[0]?.error ? esc(a.jobs[0].error) : "No jobs in the queue.");
  table(document.getElementById("tasks"), [
    ["When", t => ago(t.created)], ["Kind", t => esc(t.kind)], ["Stage", t => esc(t.stage), "mono"],
    ["Batches", t => t.batches.length], ["Status", t => st(t.status)],
    ["Job", t => esc(t.job_id || ""), "mono"],
    ["", t => (t.log ? logBtn(t.log) + " " : "") + `<button class="link" data-task="${t.id}">output</button>`],
  ], a.tasks, "Nothing submitted from this dashboard session.");
  table(document.getElementById("staging"), [
    ["Batch", r => esc(r.batch_id), "mono"], ["Stage", r => esc(r.stage), "mono"],
    ["Status", r => st(r.status)], ["Updated", r => ago(r.updated_at)],
    ["Error", r => esc(r.error_summary || "")],
  ], a.staging, "No transfers in flight.");
  table(document.getElementById("runs"), [
    ["Batch", r => `<button class="link mono" data-batch="${esc(r.batch_id)}">${esc(r.batch_id)}</button>`],
    ["Stage", r => esc(r.stage), "mono"], ["Status", r => st(r.status)],
    ["Units ok/fail", r => `${r.n_units_succeeded}/${r.n_units_failed}`],
    ["Took", r => dur(r.duration_ms)], ["Ended", r => ago(r.ended_at)],
  ], a.recent_runs);
  table(document.getElementById("leases"), [
    ["Batch", r => esc(r.batch_id), "mono"], ["Stage", r => esc(r.stage), "mono"],
    ["State", r => r.active ? st("active") : '<span class="muted">expired</span>'],
    ["Job", r => esc(r.slurm_job_id || ""), "mono"], ["Claimed", r => ago(r.claimed_at)],
  ], a.leases, "No leases.");
  document.getElementById("updated").textContent = `updated ${new Date().toLocaleTimeString()}`;
}

let HIST = [];
const BAD_STATES = ["FAILED", "TIMEOUT", "OUT_OF_MEMORY", "NODE_FAIL", "CANCELLED", "BOOT_FAIL", "PREEMPTED"];
async function loadHistory() {
  const h = await api("/api/history");
  HIST = h.jobs;
  renderHistory();
}
function renderHistory() {
  const el = document.getElementById("history");
  if (HIST[0]?.error) { el.innerHTML = `<tr><td class="s-failed">${esc(HIST[0].error)}</td></tr>`; return; }
  const counts = {};
  for (const j of HIST) counts[j.state] = (counts[j.state] || 0) + 1;
  document.getElementById("hSummary").innerHTML =
    Object.entries(counts).sort((a, b) => b[1] - a[1]).map(([k, v]) => `<span class="chip">${st(k)} ${v}</span>`).join("");
  const q = document.getElementById("hName").value.trim().toLowerCase();
  const sf = document.getElementById("hState").value;
  const rows = HIST.filter(j => (!q || j.name.toLowerCase().includes(q)) &&
    (!sf || (sf === "bad" ? BAD_STATES.includes(j.state) : j.state === sf)));
  const when = t => t && t !== "Unknown" && t !== "None" ? esc(t.replace("T", " ").slice(5, 16)) : "—";
  table(el, [
    ["Job", j => esc(j.job_id), "mono"], ["Name", j => esc(j.name), "mono"], ["State", j => st(j.state)],
    ["Start", j => when(j.start)], ["End", j => j.state === "RUNNING" ? "running" : when(j.end)],
    ["Elapsed", j => esc(j.elapsed)], ["Exit", j => esc(j.exit_code), "mono"], ["Node", j => esc(j.nodes), "mono"],
    ["Logs", j => (j.stdout || j.stderr)
      ? logBtn(j.stdout, "out") + (j.stderr && j.stderr !== j.stdout ? " " + logBtn(j.stderr, "err") : "")
      : '<span class="muted">no log</span>'],
  ], rows.slice(0, 500), HIST.length ? "No jobs match the filter." : "No jobs in the last 48 hours.");
}

const REOPEN = new Set();
async function loadSync() {
  const y = await api("/api/sync");
  if (y.error) { document.getElementById("syMeta").innerHTML = `<span class="s-failed">${esc(y.error)}</span>`; return; }
  document.getElementById("syConfig").textContent = y.config;
  const total = {}, byStage = {};
  for (const c of y.counts) {
    total[c.status] = (total[c.status] || 0) + c.n;
    (byStage[c.stage] ||= []).push(`${st(c.status)} ${c.n}`);
  }
  const box = s => `<div class="st"><div class="note">${st(s)}</div><div class="big">${total[s] || 0}</div></div>`;
  const main = y.states.slice(0, 5), term = y.states.slice(5);
  document.getElementById("syFlow").innerHTML =
    `<div class="st"><div class="note">inbox, unregistered</div><div class="big">${y.inbox.unregistered.length}</div></div>
     <span class="arrow">→</span>` +
    main.map(box).join('<span class="arrow">→</span>') + '<span class="sep"></span>' + term.map(box).join("");
  const snap = y.snapshot.mtime ? `published ${ago(y.snapshot.mtime)} (${(y.snapshot.size / 1e9).toFixed(1)} GB)` : "not published yet";
  document.getElementById("syMeta").innerHTML =
    `${Object.entries(byStage).map(([k, v]) => `<span class="mono">${esc(k)}</span>: ${v.join(", ")}`).join(" · ") || "No result syncs yet."}
     <br>inbox <span class="mono">${esc(y.inbox.path)}</span>: ${y.inbox.files} request file(s) ·
     snapshot <span class="mono">${esc(y.snapshot.path)}</span>: ${snap}`;
  const ids = new Set(y.outstanding.map(r => r.run_id));
  for (const id of [...REOPEN]) if (!ids.has(id)) REOPEN.delete(id);
  table(document.getElementById("syOut"), [
    ["", r => ["failed", "canceled"].includes(r.status)
      ? `<input type="checkbox" data-reopen="${esc(r.run_id)}" ${REOPEN.has(r.run_id) ? "checked" : ""} title="reopen">` : ""],
    ["Batch", r => `<button class="link mono" data-batch="${esc(r.batch_id)}">${esc(r.batch_id)}</button>`],
    ["Stage", r => esc(r.stage), "mono"], ["Sync", r => st(r.status)], ["Run", r => st(r.run_status)],
    ["Tries", r => r.attempt_count], ["Updated", r => ago(r.updated_at)],
    ["Error", r => `<span title="${esc(r.error_summary || "")}">${esc((r.error_summary || "").slice(0, 60))}</span>`],
  ], y.outstanding, "Everything registered has been ingested.");
  table(document.getElementById("syRecent"), [
    ["Batch", r => `<button class="link mono" data-batch="${esc(r.batch_id)}">${esc(r.batch_id)}</button>`],
    ["Stage", r => esc(r.stage), "mono"], ["Run", r => st(r.run_status)],
    ["Promoted", r => r.promotion_succeeded ? "yes" : "no"], ["Ingested", r => ago(r.ingested_at)],
  ], y.recent, "Nothing ingested yet.");
  updateReopenNote();
}
function updateReopenNote() {
  document.getElementById("syReopenNote").textContent = REOPEN.size ? `${REOPEN.size} run(s) will be reopened` : "";
}
async function doSync(action) {
  const labels = {
    sync_run: `Submit sync_atlas_results.py${REOPEN.size ? ` (reopening ${REOPEN.size} run(s))` : ""}?`,
    snapshot_check: "Submit a Slurm job that copies the DB and checks reconciliation (--dry-run)?",
    snapshot_publish: document.getElementById("snTransfer").checked
      ? "Publish the snapshot AND transfer it to Atlas? Make sure the nightly copy is disabled first."
      : "Publish the Ceres DB snapshot?",
  };
  if (labels[action] && !confirm(labels[action])) return;
  const out = document.getElementById("syStatus");
  out.innerHTML = '<span class="spin"></span>';
  try {
    const t = await api("/api/sync", {
      action, reopen: [...REOPEN],
      bundle_limit: +document.getElementById("syLimit").value || 10,
      refresh_inventory: document.getElementById("syRefresh").checked,
      transfer: document.getElementById("snTransfer").checked,
    });
    if (action === "sync_run" && t.status === "submitted") { REOPEN.clear(); updateReopenNote(); }
    pollTask(t.id, "syStatus");
    loadActivity();
  } catch (e) { out.innerHTML = `<div class="warnbox">${esc(e.message)}</div>`; }
}

async function tick() {
  try { await Promise.all([loadOverview(), loadActivity(), loadSync(), loadHistory()]); }
  catch (e) { document.getElementById("updated").textContent = `refresh failed: ${e.message}`; }
}

function batches() {
  return document.getElementById("tBatches").value.split(/[\s,]+/).filter(s => s && !s.startsWith("#"));
}
function onStage() {
  const s = OV.stages[document.getElementById("tStage").value];
  document.getElementById("tSite").value = s.site;
  document.getElementById("rerunWrap").style.display = s.rerun ? "" : "none";
  if (!s.rerun) document.getElementById("tRerun").checked = false;
  updateTriggerState();
}
function updateTriggerState() {
  if (!OV) return;
  const s = OV.stages[document.getElementById("tStage").value];
  const n = batches().length;
  document.getElementById("tCount").textContent = n ? `${n} batch(es)` : "";
  const btn = document.getElementById("triggerBtn");
  btn.disabled = !n || !s.triggerable;
  btn.title = s.triggerable ? "" : `${document.getElementById("tStage").value} must be submitted from ${s.cluster}`;
  document.getElementById("previewBtn").disabled = !n;
}

async function doTask(kind) {
  const stage = document.getElementById("tStage").value;
  const b = batches();
  if (kind === "trigger" && !confirm(`Submit ${stage} chain for ${b.length} batch(es)?`)) return;
  const out = document.getElementById("tStatus");
  out.innerHTML = `<span class="spin"></span> ${kind === "preview" ? "Running dry run…" : "Submitting…"}`;
  try {
    const t = await api(`/api/${kind}`, {
      stage, batches: b.join("\n"), site: document.getElementById("tSite").value.trim(),
      rerun: document.getElementById("tRerun").checked,
    });
    pollTask(t.id);
    loadActivity();
  } catch (e) { out.innerHTML = `<div class="warnbox">${esc(e.message)}</div>`; }
}
async function pollTask(id, target = "tStatus") {
  const out = document.getElementById(target);
  const t = await api(`/api/task?id=${id}`);
  out.innerHTML = `<div class="note">${esc(t.kind)} · ${esc(t.stage)} · ${st(t.status)}
    ${t.status === "running" ? '<span class="spin"></span>' : ""} ${t.log ? logBtn(t.log, "open job log") : ""}</div>
    ${t.output ? `<pre>${esc(t.output)}</pre>` : ""}`;
  if (t.status === "running") setTimeout(() => pollTask(id, target), 3000);
}

async function lookup(id) {
  id = (id || document.getElementById("bId").value).trim();
  if (!id) return;
  document.getElementById("bId").value = id;
  const out = document.getElementById("bOut");
  out.innerHTML = '<span class="spin"></span>';
  try {
    const b = await api(`/api/batch?id=${encodeURIComponent(id)}`);
    const per = Object.keys(OV.stages).map(stage => {
      const last = b.runs.find(r => r.stage === stage);
      const lease = b.leases.find(l => l.stage === stage);
      const stg = b.staging.filter(s => s.stage === stage).map(s => s.status);
      const sync = b.syncs.find(s => s.stage === stage);
      return { stage, last, lease, sync, stg: [...new Set(stg)], ready: b.ready_for.includes(stage) };
    });
    out.innerHTML = `<table>
      <tr><th>Stage</th><th>Last run</th><th>Units ok/fail</th><th>Staging</th><th>Result sync</th><th>Lease</th><th>Ready</th></tr>
      ${per.map(p => `<tr><td class="mono">${p.stage}</td>
        <td>${p.last ? `${st(p.last.status)} ${ago(p.last.ended_at)}` : '<span class="muted">—</span>'}</td>
        <td>${p.last ? `${p.last.n_units_succeeded}/${p.last.n_units_failed}` : ""}</td>
        <td>${p.stg.map(st).join(", ")}</td>
        <td>${p.sync ? st(p.sync.status) : ""}</td>
        <td>${p.lease ? esc(p.lease.slurm_job_id || "held") : ""}</td>
        <td>${p.ready ? st("success").replace(">success<", ">yes<") : ""}</td></tr>`).join("")}
      </table>
      <div class="note" style="margin-top:6px">${b.runs.length} run(s) total ·
        <button class="link" data-addbatch="${esc(id)}">add to trigger list</button></div>`;
  } catch (e) { out.innerHTML = `<div class="warnbox">${esc(e.message)}</div>`; }
}

let dlgPath = null;
async function showLog(path) {
  dlgPath = path;
  const d = document.getElementById("dlg");
  document.getElementById("dlgTitle").textContent = path;
  document.getElementById("dlgBody").textContent = "Loading…";
  if (!d.open) d.showModal();
  try {
    const r = await api(`/api/log?path=${encodeURIComponent(path)}`);
    const body = document.getElementById("dlgBody");
    body.textContent = r.text || "(empty)";
    body.scrollTop = body.scrollHeight;
  } catch (e) { document.getElementById("dlgBody").textContent = e.message; }
}
async function showTask(id) {
  const t = await api(`/api/task?id=${id}`);
  dlgPath = null;
  document.getElementById("dlgTitle").textContent = `${t.kind} ${t.stage} — ${t.batch_file}`;
  document.getElementById("dlgBody").textContent = t.output || "(no output yet)";
  document.getElementById("dlg").showModal();
}

document.addEventListener("click", async e => {
  const d = e.target.dataset;
  if (d.log) showLog(d.log);
  else if (d.task) showTask(d.task);
  else if (d.batch) lookup(d.batch);
  else if (d.refresh) { await api("/api/refresh", { stages: [d.refresh] }); setTimeout(loadOverview, 500); }
  else if (d.use) {
    document.getElementById("tStage").value = d.use; onStage();
    document.getElementById("tBatches").value = OV.stages[d.use].ready.batch_ids.join("\n");
    updateTriggerState();
  } else if (d.addbatch) {
    const ta = document.getElementById("tBatches");
    if (!batches().includes(d.addbatch)) ta.value = (ta.value.trim() + "\n" + d.addbatch).trim();
    updateTriggerState();
  }
});
document.getElementById("refreshAll").onclick = async () => {
  const r = await api("/api/refresh", {});
  if (!r.started) alert("A readiness refresh is already running.");
  setTimeout(loadOverview, 500);
};
document.getElementById("fillReady").onclick = () => {
  const s = document.getElementById("tStage").value;
  document.getElementById("tBatches").value = OV.stages[s].ready.batch_ids.join("\n");
  updateTriggerState();
};
document.getElementById("tStage").onchange = onStage;
document.getElementById("hName").oninput = renderHistory;
document.getElementById("hState").onchange = renderHistory;
document.addEventListener("change", e => {
  const id = e.target.dataset.reopen;
  if (!id) return;
  e.target.checked ? REOPEN.add(id) : REOPEN.delete(id);
  updateReopenNote();
});
document.getElementById("syPreview").onclick = () => doSync("sync_preview");
document.getElementById("syRun").onclick = () => doSync("sync_run");
document.getElementById("snCheck").onclick = () => doSync("snapshot_check");
document.getElementById("snPublish").onclick = () => doSync("snapshot_publish");
document.getElementById("tBatches").oninput = updateTriggerState;
document.getElementById("previewBtn").onclick = () => doTask("preview");
document.getElementById("triggerBtn").onclick = () => doTask("trigger");
document.getElementById("bGo").onclick = () => lookup();
document.getElementById("bId").onkeydown = e => { if (e.key === "Enter") lookup(); };
document.getElementById("dlgClose").onclick = () => document.getElementById("dlg").close();
document.getElementById("dlgReload").onclick = () => dlgPath && showLog(dlgPath);

tick();
setInterval(tick, 15000);
</script>
</body>
</html>
"""


def load_or_create_token() -> str:
    """Reuse one token across restarts so the browser cookie keeps working."""
    try:
        token = TOKEN_FILE.read_text().strip()
        if token:
            return token
    except OSError:
        pass
    token = secrets.token_urlsafe(24)
    fd = os.open(TOKEN_FILE, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as fh:
        fh.write(token + "\n")
    return token


def write_state(state_file: Path, **state) -> None:
    """Record where the job-hosted dashboard is listening (for --connect)."""
    state_file.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(state_file, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as fh:
        json.dump({**state, "updated": utc_now()}, fh, indent=1)


def connect(state_file: Path, local_port: int, token: str) -> int:
    """Relay localhost:<local_port> on the login node to the job's node:port.

    The job lands on a different compute node every day, which a laptop
    can't reach directly; this gives it a fixed localhost address that VS
    Code (or ``ssh -L``) forwards like any other login-node port.
    """
    import asyncio

    try:
        state = json.loads(state_file.read_text())
    except (OSError, ValueError):
        state = {}
    if not state.get("running"):
        print(f"No dashboard job is running (per {state_file}).\n"
              f"Start one: cd {REPO_ROOT} && sbatch scripts/admin/dashboard.sbatch", file=sys.stderr)
        return 1
    target = (state["host"], state["port"])
    try:
        socket.create_connection(target, timeout=10).close()
    except OSError as exc:
        print(f"Dashboard job {state.get('job_id')} recorded at {target[0]}:{target[1]} "
              f"but it isn't answering ({exc}). Check: squeue --name=agir_dashboard",
              file=sys.stderr)
        return 1

    async def pipe(reader, writer):
        try:
            while data := await reader.read(65536):
                writer.write(data)
                await writer.drain()
        except (ConnectionError, OSError):
            pass
        finally:
            writer.close()

    async def handle(client_r, client_w):
        try:
            node_r, node_w = await asyncio.open_connection(*target)
        except OSError:
            client_w.close()
            return
        await asyncio.gather(pipe(client_r, node_w), pipe(node_r, client_w))

    async def serve():
        for port in range(local_port, local_port + 20):
            try:
                server = await asyncio.start_server(handle, "127.0.0.1", port)
                break
            except OSError:
                continue
        else:
            print(f"Ports {local_port}-{local_port + 19} are all in use.", file=sys.stderr)
            return 1
        print(f"AgIR dashboard (job {state.get('job_id')} on {target[0]}, "
              f"up since {state.get('started')})\n\n"
              f"  http://localhost:{port}/?token={token}\n\n"
              f"From VS Code, click the link (it forwards the port). From a plain ssh\n"
              f"session, log in with: ssh -L {port}:localhost:{port} <user>@ceres.scinet.usda.gov\n"
              f"Ctrl-C closes this relay; the dashboard job keeps running.", flush=True)
        async with server:
            await server.serve_forever()

    try:
        return asyncio.run(serve()) or 0
    except KeyboardInterrupt:
        return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="AgIR pipeline operator dashboard.")
    parser.add_argument("--db", default=DEFAULT_DB, help=f"SQLite DB (default: {DEFAULT_DB}).")
    parser.add_argument("--port", type=int, default=8765,
                        help="Listen port (0 picks a free one); with --connect, the local port.")
    parser.add_argument(
        "--host", default="127.0.0.1",
        help="Bind address; the Slurm job uses 0.0.0.0 so --connect can reach it.",
    )
    parser.add_argument(
        "--token", default=os.environ.get("AGIR_DASHBOARD_TOKEN"),
        help=f"Access token (default: $AGIR_DASHBOARD_TOKEN, else {TOKEN_FILE}, "
             "created on first use).",
    )
    parser.add_argument(
        "--state-file", type=Path, default=STATE_FILE,
        help=f"Where the job records its node/port for --connect (default: {STATE_FILE}).",
    )
    parser.add_argument(
        "--advertise-host",
        help="Host name recorded in --state-file for this server (the job's node). "
             "Setting it makes this server write the state file.",
    )
    parser.add_argument(
        "--connect", action="store_true",
        help="On the login node: relay localhost:--port to the running dashboard job "
             "and print its URL.",
    )
    parser.add_argument(
        "--refresh-on-start", action="store_true",
        help="Recompute readiness views in the background at startup.",
    )
    parser.add_argument("--log-level", default="INFO",
                        choices=["DEBUG", "INFO", "WARNING", "ERROR"])
    args = parser.parse_args()
    logging.basicConfig(level=args.log_level, format="%(asctime)s %(levelname)s %(message)s")

    token = args.token or load_or_create_token()
    if args.connect:
        return connect(args.state_file, args.port, token)

    store = Store(args.db)
    if args.refresh_on_start or not store.readiness:
        store.refresh_readiness()

    server = ThreadingHTTPServer((args.host, args.port), make_handler(store, token))
    port = server.server_address[1]
    state = {"host": args.advertise_host, "port": port,
             "job_id": os.environ.get("SLURM_JOB_ID"), "started": utc_now()}
    if args.advertise_host:
        write_state(args.state_file, **state, running=True)
        # Job logs are group-readable; keep the token out of them.
        print(f"\nAgIR dashboard on {args.advertise_host}:{port}; "
              f"connect with: dashboard.py --connect\n", flush=True)
    else:
        print(f"\nAgIR dashboard: http://localhost:{port}/?token={token}\n", flush=True)

    def on_sigterm(signum, frame):
        raise KeyboardInterrupt

    # Slurm (time limit, scancel) and `timeout` stop the job with SIGTERM.
    signal.signal(signal.SIGTERM, on_sigterm)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
        if args.advertise_host:
            write_state(args.state_file, **state, running=False)
    return 0


if __name__ == "__main__":
    sys.exit(main())
