MD:
  weeds 2022:
    start: "2022-03-04"
    end: "2022-10-17"
    bbot_version: 2.0
    crs: LOCAL
    pipeline_season: summer_weeds_2022
    note: ""
  cover crops 2022/2023:
    start: "2022-10-20"
    end: "2023-04-25"
    bbot_version: 2.0
    crs: LOCAL
    pipeline_season: cool_season_covers_2022_2023
    note: ""
  cash crops 2023:
    start: "2023-05-12"
    end: "2023-07-07"
    bbot_version: 2.0
    crs: LOCAL
    pipeline_season: summer_cash_crops_2023
    note: ""
  weeds 2023:
    start: "2023-07-17"
    end: "2023-09-17"
    bbot_version: 2.0
    crs: LOCAL
    pipeline_season: summer_weeds_2023
    note: ""
  cover crops 2023/2024:
    start: "2023-09-18"
    end: "2024-05-16"
    bbot_version: 2.0
    crs: LOCAL
    pipeline_season: cool_season_covers_2023_2024
    note: ""
  weeds 2024:
    start: "2024-07-08"
    end: "2024-09-08"
    bbot_version: 3.0
    crs: 4326
    pipeline_season: summer_weeds_2024
    note: ""
  cover crops 2024/2025_MDbbotv3.0:
    start: "2024-10-16"
    end: "2024-11-18"
    bbot_version: 3.0
    crs: 4326
    pipeline_season: cool_season_covers_2024_2025_bbotv30
    note: ""
  cover crops 2024/2025:
    start: "2025-04-16"
    end: "2025-05-16"
    bbot_version: 3.1
    crs: 4326
    pipeline_season: cool_season_covers_2024_2025
    note: ""
  weeds_2025:
    start: "2025-06-06"
    end: "2025-07-28"
    bbot_version: 3.1
    crs: 32618
    pipeline_season: summer_weeds_2025
    gh_reviewer: nnotaba
    note: ""
  beets_2025:
    start: "2025-08-25"
    end: "2025-10-17"
    bbot_version: 3.1
    crs: 32618
    pipeline_season: beets_2025
    gh_reviewer: nnotaba
    note: ""
  cover crops 2025/2026:
    start: "2025-10-07"
    end: "2026-05-10"
    bbot_version: 3.1
    crs: 32618
    pipeline_season: cover_crops_2025_2026
    gh_reviewer: nnotaba
    note: ""
  weeds_2026:
    start: "2026-06-15"
    end: "2026-07-30"
    bbot_version: 3.1
    crs: 32618
    pipeline_season: summer_weeds_2026
    gh_reviewer: nnotaba
    note: ""

NC:
  weeds 2022:
    start: "2022-03-04"
    end: "2022-09-23"
    bbot_version: 2.0
    crs: LOCAL
    pipeline_season: summer_weeds_2022
    note: ""
  cover crops 2022/2023:
    start: "2022-10-11"
    end: "2023-03-30"
    bbot_version: 2.0
    crs: LOCAL
    pipeline_season: cool_season_covers_2022_2023
    note: ""
  cash crops 2023:
    start: "2023-06-06"
    end: "2023-07-25"
    bbot_version: 2.0
    crs: LOCAL
    pipeline_season: summer_cash_crops_2023
    note: ""
  weeds 2023:
    start: "2023-08-21"
    end: "2023-10-10"
    bbot_version: 2.0
    crs: LOCAL
    pipeline_season: summer_weeds_2023
    note: ""
  cover crops 2023/2024:
    start: "2023-10-11"
    end: "2024-03-14"
    bbot_version: 2.0
    crs: LOCAL
    pipeline_season: cool_season_covers_2023_2024
    note: ""
  weeds 2024:
    start: "2024-07-08"
    end: "2024-10-08"
    bbot_version: 3.0
    crs: 4326
    pipeline_season: summer_weeds_2024
    note: ""
  cover crops 2024/2025:
    start: "2024-12-02"
    end: "2025-04-15"
    bbot_version: 3.1
    crs: 4326
    pipeline_season: cool_season_covers_2024_2025_NCpos2
    note: ""
  # cash crops 2025:
  #   start: "2025-06-01"
  #   end: "2025-07-01"
  #   bbot_version: 3.1
  #   crs: 32617
  #   pipeline_season: cash_crop_dicamba_2025
  #   gh_reviewer: map0425
  # cash crops 2025_1:
  #   start: "2025-07-02"
  #   end: "2025-07-16"
  #   bbot_version: 3.1
  #   crs: 32617
  #   pipeline_season: cash_crop_dicamba_2025_dap30
  #   gh_reviewer: map0425
  dicamba 2025:
    start: "2025-06-01"
    end: "2025-08-08"
    bbot_version: 3.1
    crs: 32617
    pipeline_season: cash_crop_dicamba_2025_dap30_v2
    gh_reviewer: map0425
    note: "No reconstruction necessary, all instances are labeled as soybean."
  zoysia 2025:
    start: "2025-08-25"
    end: "2025-09-27"
    bbot_version: 3.1
    crs: 32617
    pipeline_season: zoysia_2025
    gh_reviewer: map0425
    note: ""
  cover crops 2025/2026:
    start: "2025-11-10"
    end: "2026-05-01"
    bbot_version: 3.1
    crs: 32617
    pipeline_season: cover_crops_2025_2026
    gh_reviewer: map0425
    note: ""
  peanuts 2026:
    start: "2026-06-04"
    end: "2026-09-01"
    bbot_version: 3.1
    crs: 32617
    pipeline_season: peanuts_2026
    gh_reviewer: map0425
    note: ""

TX:
  weeds 2022:
    start: "2022-03-04"
    end: "2022-10-24"
    bbot_version: 2.0
    crs: LOCAL
    pipeline_season: summer_weeds_2022
    note: ""
  cover crops 2022/2023:
    start: "2022-10-25"
    end: "2023-04-04"
    bbot_version: 2.0
    crs: LOCAL
    pipeline_season: cool_season_covers_2022_2023
    note: ""
  cash crops 2023:
    start: "2023-05-08"
    end: "2023-08-01"
    bbot_version: 2.0
    crs: LOCAL
    pipeline_season: summer_cash_crops_2023
    note: ""
  weeds 2023:
    start: "2023-08-04"
    end: "2023-10-19"
    bbot_version: 2.0
    crs: LOCAL
    pipeline_season: summer_weeds_2023
    note: ""
  cover crops 2023/2024:
    start: "2023-10-20"
    end: "2024-03-01"
    bbot_version: 2.0
    crs: LOCAL
    pipeline_season: cool_season_covers_2023_2024
    note: ""
  weeds 2024:
    start: "2024-03-26"
    end: "2024-09-08"
    bbot_version: 2.0
    crs: LOCAL
    pipeline_season: summer_weeds_2024
    note: ""
  weeds 2025:
    start: "2025-06-09"
    end: "2025-11-16"
    bbot_version: 3.1
    crs: 32614
    pipeline_season: summer_weeds_2025
    gh_reviewer: mkutu
    note: ""


season_mappings:
  summer_weeds_2024:
    - "weeds 2024"
    - "weeds_2024"
    - "summer_weeds_2024"
    - "summer weeds 2024"
  summer_weeds_2025:
    - "weeds 2025"
    - "weeds_2025"
    - "summer_weeds_2025"
    - "summer weeds 2025"
  cash_crop_dicamba_2025:
    - "cash_crop_dicamba_2025_dap30"
    - "cash_crop_dicamba_2025_dap30_v2"
    - "dicamba_2025"
  cover_crops_2025_2026:
    - "cover crops 2025/2026"
    - "cover_crops_2025_2026"
    - "cover crops 2025 2026"
    - "cool season covers 2025 2026"
    - "cool_season_covers_2025_2026"
  cool_season_covers_2024_2025_bbotv30:
    - "cover crops 2024/2025_MDbbotv3.0"
    - "cool_season_covers_2024_2025_bbotv30"
    - "cool season covers 2024 2025 bbotv30"
  cool_season_covers_2024_2025:
    - "cover crops 2024/2025"
    - "cool_season_covers_2024_2025"
    - "cool season covers 2024 2025"
  cool_season_covers_2024_2025_NCpos2:
    - "cool_season_covers_2024_2025_NCpos2"
    - "cool season covers 2024 2025 ncpos2"
  zoysia_2025:
    - "zoysia_2025"
  beets_2025:
    - "beets_2025"
