# Which report and what to move
report:
  csv_path: /project/dash_agir/matthew.kutugata/repos/agir-db/reports/globus_index/raw/2025-12-08_sync_batches_needing_juno_copy_images_and_metadata.csv
  batch_column: batch_id

transfer:
  juno_endpoint: "904c2108-90cf-11e8-9672-0a6d4e044368"
  ncsu_endpoint: "2f7f6170-8d5c-11e9-8e6a-029d279f7e24"
  ceres_endpoint: "f45a24f8-09ba-11ec-b342-1feaf93e3729"

  source_mode: testing_ncsu # production / testing_ncsu

  # Submit real Globus transfer when false.
  dry_run: true

  # Polling controls for requested -> active -> completed/failed lifecycle.
  poll_interval_seconds: 10
  poll_timeout_seconds: 1800
  max_poll_attempts: 180

  # Stage/data-state transfer routes.
  routes:
    raw_to_jpg:
      data_state: semifield-upload
      source_root_juno: /LTS/project/dash_agir/semifield-upload
      source_root_ncsu: /tmp/agir/LTS/NC_2025-12-03/images/upload_raw
      destination_root: /90daydata/dash_agir/semifield-upload
    post_raw_to_jpg:
      data_state: semifield-developed-images
      source_root_juno: /LTS/project/dash_agir/semifield-developed-images
      source_root_ncsu: /tmp/agir/LTS/NC_2025-12-03/images/developed_images
      destination_root: /90daydata/dash_agir/semifield-developed-images

  location_priority:
    # - CERES
    # - NCSU

  lts_root_priority:
    # - /LTS/project/dash_agir
    # - /project/dash_agir
    # - /90day/dash_agir