STAGE = "det_to_world"
STAGE_VERSION = "0.3.0"

ERROR_REMAP_FAILED = "E_REMAP_FAILED"
ERROR_CSV_INVALID = "E_CSV_INVALID"
ERROR_SHAPEFILE_UNREADABLE = "E_SHAPEFILE_UNREADABLE"
ERROR_SPATIAL_JOIN_FAILED = "E_SPATIAL_JOIN_FAILED"
ERROR_UNKNOWN_SPECIES_CODE = "E_UNKNOWN_SPECIES_CODE"
ERROR_PRIMARY_SELECTION_FAILED = "E_PRIMARY_SELECTION_FAILED"

WARNING_ZONE_TOO_FAR = "W_ZONE_TOO_FAR"
WARNING_NO_DETECTION_FILE = "W_NO_DETECTION_FILE"
