STAGE = "det_to_world"
STAGE_VERSION = "0.1.0"

ERROR_GRID_NOT_FOUND = "E_GRID_NOT_FOUND"
ERROR_REMAP_FAILED = "E_REMAP_FAILED"
ERROR_CSV_INVALID = "E_CSV_INVALID"
ERROR_SHAPEFILE_UNREADABLE = "E_SHAPEFILE_UNREADABLE"
ERROR_SPATIAL_JOIN_FAILED = "E_SPATIAL_JOIN_FAILED"
